import {
  buildClinicalIndexes,
  buildReferenceMap,
  type ClinicalContentStore,
  type ConditionDeepView,
  type ConditionQuickView,
  type ViewDensity,
  toConditionView,
} from '@/lib/clinicalContentModel';

export const clinicalSeed: ClinicalContentStore = {
  bodyRegions: [
    {
      id: 'region-shoulder',
      key: 'shoulder',
      name: 'Shoulder',
      aliases: ['Glenohumeral region', 'Subacromial region'],
      tags: ['upper-quarter', 'overhead-athlete'],
    },
  ],
  references: [
    {
      id: 'ref-rcsp-cpg-2022',
      shortLabel: 'JOSPT CPG 2022',
      type: 'guideline',
      title: 'Rotator Cuff Tendinopathy Diagnosis, Non-surgical Medical Care, and Rehabilitation: A Clinical Practice Guideline',
      authors: ['Ludewig PM', 'Reiman MP', 'et al.'],
      year: 2022,
      journalOrSource: 'Journal of Orthopaedic & Sports Physical Therapy',
      doi: '10.2519/jospt.2022.0302',
      url: 'https://www.jospt.org/doi/10.2519/jospt.2022.0302',
    },
    {
      id: 'ref-hawkins-meta',
      shortLabel: 'Hegedus 2012',
      type: 'systematic-review',
      title: 'Physical examination tests of the shoulder: a systematic review with meta-analysis of individual tests',
      authors: ['Hegedus EJ', 'Goode A', 'Campbell S', 'et al.'],
      year: 2012,
      journalOrSource: 'British Journal of Sports Medicine',
      doi: '10.1136/bjsports-2012-091066',
      url: 'https://bjsm.bmj.com/content/46/14/964',
    },
    {
      id: 'ref-quickdash',
      shortLabel: 'QuickDASH validation',
      type: 'cohort',
      title: 'The QuickDASH outcome measure: reliability and validity in upper-extremity disorders',
      authors: ['Beaton DE', 'Wright JG', 'Katz JN'],
      year: 2005,
      journalOrSource: 'Journal of Bone and Joint Surgery',
    },
    {
      id: 'ref-red-flag-cancer',
      shortLabel: 'NICE NG12',
      type: 'guideline',
      title: 'Suspected cancer: recognition and referral',
      authors: ['National Institute for Health and Care Excellence'],
      year: 2023,
      journalOrSource: 'NICE guideline NG12',
      url: 'https://www.nice.org.uk/guidance/ng12',
    },
  ],
  specialTests: [
    {
      id: 'test-hawkins-kennedy',
      title: 'Hawkins-Kennedy Test',
      aliases: ['Hawkins test'],
      assesses: 'Subacromial pain provocation / rotator cuff related shoulder pain cluster',
      bodyRegionId: 'region-shoulder',
      targetStructureOrDiagnosis: 'Rotator cuff related shoulder pain',
      testPurpose: 'Symptom provocation as part of a shoulder pain diagnostic cluster, not a stand-alone diagnosis.',
      patientPosition: 'Sitting or standing; shoulder and elbow flexed to approximately 90 degrees.',
      clinicianAction: [
        'Stabilize scapula and proximal humerus.',
        'Passively internally rotate the humerus in horizontal adduction.',
      ],
      positiveFinding: 'Reproduction of familiar anterolateral shoulder pain.',
      interpretation: 'Supports subacromial pain hypothesis when combined with history and other exam findings.',
      limitations: [
        'Can be positive in multiple shoulder pain diagnoses.',
        'Irritable shoulders may react to non-specific compression pain.',
      ],
      diagnosticUtilityNotes: [
        'Use as part of a test cluster and load response findings.',
        'Avoid over-reliance on sensitivity/specificity from single studies.',
      ],
      evidenceNotes: 'Moderate-quality evidence suggests limited stand-alone utility; better when integrated with cluster reasoning.',
      relatedConditionIds: ['condition-rcrsp'],
      referenceIds: ['ref-hawkins-meta', 'ref-rcsp-cpg-2022'],
    },
  ],
  treatments: [
    {
      id: 'tx-education-load-modification',
      title: 'Education + Load Modification',
      aliases: ['Activity modification coaching'],
      whatItIs: 'Collaborative planning of symptom-guided loading, sleep/posture factors, and realistic recovery expectations.',
      whenToUse: ['Early management of irritable shoulder pain.', 'When pain behaviors or fear are limiting movement exposure.'],
      whenNotToOveruse: ['Do not prolong unloading past symptom settling window.', 'Avoid framing pain as tissue damage certainty.'],
      stageRelevance: ['acute-irritable', 'subacute', 'chronic'],
      indications: ['Night pain with high irritability.', 'Pain spike after rapid load increase.'],
      contraindicationsPrecautions: ['Screen for non-musculoskeletal red flags before conservative care-only approach.'],
      evidenceSummary: 'Strong guideline-level support as a first-line component, especially when combined with progressive exercise.',
      referenceIds: ['ref-rcsp-cpg-2022'],
    },
  ],
  exerciseProgressions: [
    {
      id: 'ex-shoulder-isometric-to-isotonic-abduction',
      title: 'Rotator Cuff Loading Progression: Isometric to Isotonic Abduction',
      aliases: ['Shoulder abduction loading ladder'],
      targetConditionIds: ['condition-rcrsp'],
      targetTissuesFunctions: ['Supraspinatus/infraspinatus load tolerance', 'Scapulohumeral control'],
      stage: 'subacute',
      entryCriteria: ['Resting pain stable for 48-72 hours.', 'Able to elevate arm to 90 degrees with acceptable pain response.'],
      dosageSuggestions: ['Isometric: 5 x 30-45 second holds @ 4-6/10 effort.', 'Isotonic: 3 x 8-12 reps, 2-3 sessions/week.'],
      commonCompensations: ['Upper trapezius dominance / shoulder hiking', 'Lumbar extension to substitute elevation'],
      progressionOptions: ['Increase lever arm or external load.', 'Advance to 90-120 degree scaption arc.'],
      regressionOptions: ['Reduce arc to pain-tolerable range.', 'Return to shorter isometric holds with lower effort.'],
      returnToFunctionRelevance: 'Builds overhead tolerance for work, ADLs, and graded return to sport.',
      evidenceNotes: 'Progressive resistance shows superior medium-term outcomes versus passive care alone for rotator cuff related shoulder pain.',
      referenceIds: ['ref-rcsp-cpg-2022'],
    },
  ],
  outcomeMeasures: [
    {
      id: 'om-quickdash',
      title: 'QuickDASH',
      aliases: ['Quick Disabilities of the Arm, Shoulder and Hand'],
      bodyRegionId: 'region-shoulder',
      population: 'Adults with upper-extremity musculoskeletal disorders.',
      conditionRelevanceConditionIds: ['condition-rcrsp'],
      administration: ['11-item self-report questionnaire.', 'Score each item 1-5 and transform to 0-100 scale.'],
      scoring: ['Higher score = greater disability.', 'Track change over 2-6 week intervals in active rehab.'],
      mcidMdc: ['MCID often reported around 8-15 points depending on population.', 'Use local population benchmarks when available.'],
      interpretation: ['Combine with pain intensity and function-specific goals.', 'Large score shifts without functional changes should prompt context review.'],
      referenceIds: ['ref-quickdash'],
    },
  ],
  redFlags: [
    {
      id: 'redflag-nonmechanical-night-pain-weight-loss',
      title: 'Potential Serious Pathology in Shoulder Pain Presentation',
      aliases: ['Cancer red flag cluster'],
      scenario: 'Shoulder pain that is progressive, non-mechanical, severe at night, with unexplained weight loss or systemic malaise.',
      whyItMatters: 'Can indicate metastatic or primary pathology requiring urgent medical workup.',
      whatToAsk: ['Unintentional weight loss?', 'History of cancer?', 'Fever, night sweats, persistent fatigue?'],
      whatToLookFor: ['Pain not modified by movement/load.', 'Visible wasting or unexplained neurological deficits.'],
      escalationPathway: ['Stop routine load progression.', 'Communicate concern and same-day medical referral.', 'Document safety-net advice and follow-up contact.'],
      referralUrgency: 'urgent-24h',
      referenceIds: ['ref-red-flag-cancer'],
    },
  ],
  conditions: [
    {
      id: 'condition-rcrsp',
      title: 'Rotator Cuff Related Shoulder Pain',
      aliases: ['RCRSP', 'Subacromial shoulder pain syndrome'],
      bodyRegionId: 'region-shoulder',
      clinicalSnapshot: 'Load-sensitive shoulder pain with painful arc and reduced tolerance for overhead tasks, usually without full-thickness traumatic tear signs.',
      typicalPattern: [
        'Pain aggravated by overhead loading, reaching, and side-lying on involved shoulder.',
        'Variable night pain and morning stiffness lasting under 30 minutes in non-inflammatory presentations.',
      ],
      commonSubjectiveClues: [
        'Pain after abrupt training/volume increase.',
        'Difficulty with hand-behind-back tasks and overhead dressing.',
        'Temporary easing with relative rest but flare on reload.',
      ],
      objectiveExamPriorities: [
        'Asterisk signs: painful arc, resisted abduction/external rotation symptom response.',
        'Rule in/out cervical contribution and glenohumeral stiffness pattern.',
        'Assess irritability to set initial loading threshold.',
      ],
      keyDifferentialConditionIds: ['condition-adhesive-capsulitis'],
      specialTestIds: ['test-hawkins-kennedy'],
      stageBasedManagement: [
        {
          stage: 'acute-irritable',
          goals: ['Reduce symptom volatility.', 'Maintain tolerated shoulder movement.'],
          treatmentIds: ['tx-education-load-modification'],
          progressionFocus: ['Short-lever isometrics', 'Sleep and daily load adjustments'],
          reassessmentPriorities: ['Night pain trend', '24-hour response to loading'],
        },
        {
          stage: 'subacute',
          goals: ['Restore force production and confidence with overhead function.'],
          treatmentIds: ['tx-education-load-modification'],
          progressionFocus: ['Progressive resistance through tolerated arcs'],
          reassessmentPriorities: ['QuickDASH trend', 'Task-specific tolerance'],
        },
      ],
      exerciseProgressionByStage: [
        {
          stage: 'subacute',
          exerciseProgressionIds: ['ex-shoulder-isometric-to-isotonic-abduction'],
          rationale: 'Bridges analgesic loading into strength-endurance progression for daily and sport demands.',
        },
      ],
      healingRecoveryTimeline: ['Irritability reduction in 2-6 weeks with consistent load management.', 'Functional recovery commonly 6-16 weeks depending on chronicity and workload.'],
      redFlagTopicIds: ['redflag-nonmechanical-night-pain-weight-loss'],
      commonMistakesPitfalls: ['Using provocative impingement tests as sole diagnosis.', 'Progressing overhead load despite >24-hour symptom flare pattern.'],
      evidenceSummary: 'Best-supported care combines education, load modification, and progressive exercise; passive modalities are adjuncts rather than central treatment.',
      referenceIds: ['ref-rcsp-cpg-2022', 'ref-hawkins-meta'],
      evidenceStrengthTags: ['high', 'moderate'],
      lastReviewed: {
        reviewer: 'Clinical Content Team',
        reviewedAtIso: '2026-03-31',
        nextReviewDueIso: '2027-03-31',
      },
    },
    {
      id: 'condition-adhesive-capsulitis',
      title: 'Adhesive Capsulitis',
      aliases: ['Frozen shoulder'],
      bodyRegionId: 'region-shoulder',
      clinicalSnapshot: 'Stiff painful shoulder with progressive capsular pattern ROM loss and disproportionate night symptoms.',
      typicalPattern: ['Global active and passive ROM restriction, especially external rotation.'],
      commonSubjectiveClues: ['Gradual onset stiffness', 'Marked limitation with grooming/dressing tasks'],
      objectiveExamPriorities: ['Confirm capsular pattern and compare passive vs active limits'],
      keyDifferentialConditionIds: ['condition-rcrsp'],
      specialTestIds: [],
      stageBasedManagement: [],
      exerciseProgressionByStage: [],
      healingRecoveryTimeline: ['Often prolonged recovery over 12-24 months with stage-dependent symptoms.'],
      redFlagTopicIds: [],
      commonMistakesPitfalls: ['Overloading painful stiff phase with aggressive high-irritability stretching.'],
      evidenceSummary: 'Education and staged mobility/loading are central, with referral options considered in refractory cases.',
      referenceIds: ['ref-rcsp-cpg-2022'],
      evidenceStrengthTags: ['moderate'],
      lastReviewed: {
        reviewer: 'Clinical Content Team',
        reviewedAtIso: '2026-03-31',
        nextReviewDueIso: '2027-03-31',
      },
    },
  ],
};

export const clinicalSeedIndexes = buildClinicalIndexes(clinicalSeed);
export const clinicalReferenceMap = buildReferenceMap(clinicalSeed.references);

export function getConditionViewSamples(view: 'quick'): ConditionQuickView[];
export function getConditionViewSamples(view: 'deep'): ConditionDeepView[];
export function getConditionViewSamples(view: ViewDensity): Array<ConditionQuickView | ConditionDeepView> {
  return clinicalSeed.conditions.map((condition) => toConditionView(condition, view));
}
