import {
  buildClinicalIndexes,
  buildReferenceMap,
  type ClinicalContentStore,
  type ConditionDeepView,
  type ConditionQuickView,
  type ViewDensity,
  toConditionView,
} from '@/lib/clinicalContentModel';

const REVIEW_METADATA = {
  reviewer: 'Clinical Content Team',
  reviewedAtIso: '2026-04-01',
  nextReviewDueIso: '2027-04-01',
};

export const clinicalSeed: ClinicalContentStore = {
  bodyRegions: [
    { id: 'region-shoulder', key: 'shoulder', name: 'Shoulder', aliases: ['Glenohumeral region'], tags: ['upper-quarter'] },
    { id: 'region-knee', key: 'knee', name: 'Knee', aliases: ['Tibiofemoral region'], tags: ['lower-quarter'] },
    { id: 'region-ankle-foot', key: 'ankle-foot', name: 'Ankle & Foot', aliases: ['Talocrural and foot complex'], tags: ['running', 'sport'] },
    { id: 'region-lumbar-spine', key: 'lumbar-spine', name: 'Lumbar Spine', aliases: ['Low back'], tags: ['spine'] },
    { id: 'region-cervical-spine', key: 'cervical-spine', name: 'Cervical Spine', aliases: ['Neck'], tags: ['spine'] },
    { id: 'region-elbow-forearm', key: 'elbow-forearm', name: 'Elbow & Forearm', aliases: ['Lateral elbow'], tags: ['upper-quarter'] },
    { id: 'region-hand-wrist', key: 'hand-wrist', name: 'Hand & Wrist', aliases: ['Carpal region'], tags: ['upper-quarter'] },
  ],
  references: [
    {
      id: 'ref-rcsp-cpg-2022', shortLabel: 'JOSPT RC CPG 2022', type: 'guideline',
      title: 'Rotator Cuff Tendinopathy Diagnosis, Non-surgical Medical Care, and Rehabilitation: A Clinical Practice Guideline',
      authors: ['Ludewig PM', 'Reiman MP', 'et al.'], year: 2022, journalOrSource: 'JOSPT', doi: '10.2519/jospt.2022.0302',
    },
    {
      id: 'ref-ankle-cpg-2021', shortLabel: 'Ankle CPG 2021', type: 'guideline',
      title: 'Ankle Stability and Movement Coordination Impairments: Clinical Practice Guidelines',
      authors: ['Martin RL', 'Davenport TE', 'et al.'], year: 2021, journalOrSource: 'JOSPT',
    },
    {
      id: 'ref-lbp-cpg-2021', shortLabel: 'LBP CPG 2021', type: 'guideline',
      title: 'Interventions for the Management of Acute and Chronic Low Back Pain: Revision 2021',
      authors: ['George SZ', 'Fritz JM', 'et al.'], year: 2021, journalOrSource: 'JOSPT',
    },
    {
      id: 'ref-neck-cpg-2017', shortLabel: 'Neck Pain CPG 2017', type: 'guideline',
      title: 'Neck Pain Revision 2017: Clinical Practice Guidelines',
      authors: ['Blanpied PR', 'Gross AR', 'et al.'], year: 2017, journalOrSource: 'JOSPT',
    },
    {
      id: 'ref-knee-oa-cpg-2021', shortLabel: 'Knee OA CPG 2021', type: 'guideline',
      title: 'Knee Pain and Mobility Impairments: Meniscal and Articular Cartilage Lesions and Osteoarthritis Revision 2021',
      authors: ['Willy RW', 'Hoglund LT', 'et al.'], year: 2021, journalOrSource: 'JOSPT',
    },
    {
      id: 'ref-pfp-cpg-2019', shortLabel: 'PFP CPG 2019', type: 'guideline',
      title: 'Patellofemoral Pain Clinical Practice Guideline',
      authors: ['Barton CJ', 'Willy RW', 'et al.'], year: 2019, journalOrSource: 'JOSPT',
    },
    {
      id: 'ref-acsm-loading', shortLabel: 'Progressive loading evidence', type: 'systematic-review',
      title: 'Exercise therapy and progressive resistance for musculoskeletal pain conditions',
      authors: ['Multiple authors'], year: 2020, journalOrSource: 'Systematic review summary',
      notes: 'Editorial follow-up: replace with condition-specific high-priority reviews in next cycle.',
    },
    {
      id: 'ref-red-flag-cancer', shortLabel: 'NICE NG12', type: 'guideline',
      title: 'Suspected cancer: recognition and referral',
      authors: ['National Institute for Health and Care Excellence'], year: 2023, journalOrSource: 'NICE guideline NG12',
      url: 'https://www.nice.org.uk/guidance/ng12',
    },
    {
      id: 'ref-ottawa-ankle-rule', shortLabel: 'Ottawa Ankle Rules', type: 'diagnostic-study',
      title: 'Implementation of the Ottawa ankle rules', authors: ['Stiell IG', 'et al.'], year: 1994, journalOrSource: 'JAMA', doi: '10.1001/jama.271.11.827',
    },
    {
      id: 'ref-lachman-evidence', shortLabel: 'ACL exam meta-analysis', type: 'systematic-review',
      title: 'Clinical diagnosis of anterior cruciate ligament rupture: a meta-analysis',
      authors: ['Benjaminse A', 'et al.'], year: 2006, journalOrSource: 'J Orthop Sports Phys Ther',
    },
    {
      id: 'ref-carpal-tunnel', shortLabel: 'CTS guideline', type: 'guideline',
      title: 'Carpal tunnel syndrome: evidence review for diagnosis and conservative care', authors: ['AAOS and other summaries'], year: 2016, journalOrSource: 'Guideline summary',
      notes: 'Editorial follow-up: replace with latest full-text CTS CPG citations.',
    },
    {
      id: 'ref-dequervain', shortLabel: 'de Quervain evidence', type: 'cohort',
      title: 'Conservative care for de Quervain tenosynovitis: splinting, exercise, and injection pathways', authors: ['Mixed sources'], year: 2018, journalOrSource: 'Review summary',
      notes: 'Editorial follow-up: add higher-quality RCT/meta-analysis links.',
    },
    {
      id: 'ref-outcome-measures', shortLabel: 'Outcome measure psychometrics', type: 'systematic-review',
      title: 'Measurement properties for common MSK outcome measures', authors: ['Multiple'], year: 2019, journalOrSource: 'Review summary',
      notes: 'Editorial follow-up: replace with measure-specific primary sources.',
    },
  ],
  specialTests: [
    {
      id: 'test-hawkins-kennedy', title: 'Hawkins-Kennedy Test', aliases: ['Hawkins test'], assesses: 'Subacromial pain provocation', bodyRegionId: 'region-shoulder',
      targetStructureOrDiagnosis: 'Rotator cuff related shoulder pain', testPurpose: 'Used in a cluster for shoulder pain classification.',
      patientPosition: 'Sitting or standing, shoulder and elbow flexed near 90°.', clinicianAction: ['Stabilize shoulder.', 'Passively internally rotate.'],
      positiveFinding: 'Familiar anterolateral shoulder pain.', interpretation: 'Supports RCRSP hypothesis when combined with load response and history.',
      limitations: ['Not specific as a stand-alone test.'], diagnosticUtilityNotes: ['Use with resisted cuff testing and symptom behavior.'],
      evidenceNotes: 'Moderate evidence in cluster-based exam reasoning.', relatedConditionIds: ['condition-rcrsp'], referenceIds: ['ref-rcsp-cpg-2022'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'test-apprehension-relocation', title: 'Apprehension/Relocation Test', aliases: ['Anterior instability test'], assesses: 'Anterior shoulder instability', bodyRegionId: 'region-shoulder',
      targetStructureOrDiagnosis: 'Shoulder instability', testPurpose: 'Assesses apprehension with abduction-external rotation positions.',
      patientPosition: 'Supine, shoulder abducted with external rotation progression.', clinicianAction: ['Move to apprehension position.', 'Apply posterior relocation force.'],
      positiveFinding: 'Apprehension that eases with relocation force.', interpretation: 'Supports instability pattern in context of traumatic episode.',
      limitations: ['Guarding can limit interpretation.'], diagnosticUtilityNotes: ['Prioritize apprehension over pain-only response.'], evidenceNotes: 'Useful with history of dislocation/subluxation.',
      relatedConditionIds: ['condition-shoulder-instability'], referenceIds: ['ref-acsm-loading'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'test-lachman', title: 'Lachman Test', aliases: ['Anterior stability test'], assesses: 'ACL integrity', bodyRegionId: 'region-knee',
      targetStructureOrDiagnosis: 'ACL tear', testPurpose: 'Primary laxity test after pivoting/twisting injury.', patientPosition: 'Supine, knee 20-30° flexion.',
      clinicianAction: ['Stabilize femur.', 'Translate tibia anteriorly and assess end-feel.'], positiveFinding: 'Increased translation/soft end-feel vs other side.',
      interpretation: 'Raises suspicion for ACL injury.', limitations: ['Acute pain and guarding can obscure findings.'], diagnosticUtilityNotes: ['Combine with effusion timeline and mechanism.'],
      evidenceNotes: 'Higher-yield ACL test but still part of cluster.', relatedConditionIds: ['condition-acl-rehab-overview'], referenceIds: ['ref-lachman-evidence'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'test-thessaly', title: 'Thessaly (20°) Test', aliases: [], assesses: 'Meniscal irritation', bodyRegionId: 'region-knee', targetStructureOrDiagnosis: 'Meniscal pathology',
      testPurpose: 'Provocation test for mechanical meniscal symptoms.', patientPosition: 'Standing single-leg support near 20° knee flexion.', clinicianAction: ['Support patient safety.', 'Guide tibial rotation on femur.'],
      positiveFinding: 'Joint-line pain/catching similar to complaint.', interpretation: 'Supports meniscal involvement when paired with locking/catching history.',
      limitations: ['Acute irritable knee may not tolerate test.'], diagnosticUtilityNotes: ['Do not use as sole rule-in test.'], evidenceNotes: 'Variable diagnostic performance across settings.',
      relatedConditionIds: ['condition-meniscal-irritation'], referenceIds: ['ref-knee-oa-cpg-2021'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'test-valgus-stress-30', title: 'Valgus Stress Test (30°)', aliases: [], assesses: 'MCL laxity', bodyRegionId: 'region-knee', targetStructureOrDiagnosis: 'MCL sprain',
      testPurpose: 'Screens medial collateral ligament integrity.', patientPosition: 'Supine with knee at 30° flexion.', clinicianAction: ['Stabilize lateral femur.', 'Apply medial opening force at tibia.'],
      positiveFinding: 'Pain and/or excess medial gapping.', interpretation: 'Supports MCL injury severity grading with tenderness and swelling profile.', limitations: ['Pain-limited guarding in acute phase.'],
      diagnosticUtilityNotes: ['Compare with 0° valgus for broader ligament involvement.'], evidenceNotes: 'Commonly used orthopedic exam with moderate face validity.', relatedConditionIds: ['condition-mcl-sprain'], referenceIds: ['ref-knee-oa-cpg-2021'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'test-ottawa-ankle', title: 'Ottawa Ankle Rules', aliases: ['OAR'], assesses: 'Need for radiography after trauma', bodyRegionId: 'region-ankle-foot', targetStructureOrDiagnosis: 'Acute ankle/foot fracture screening',
      testPurpose: 'Rules-in imaging need in acute ankle injury.', patientPosition: 'Standing or supine.', clinicianAction: ['Palpate Ottawa points.', 'Check ability to take four steps.'],
      positiveFinding: 'Point tenderness at Ottawa sites and/or inability to bear weight.', interpretation: 'Positive rule supports imaging referral.', limitations: ['Only validated for acute trauma scenarios.'],
      diagnosticUtilityNotes: ['Not a ligament grading test.'], evidenceNotes: 'High-sensitivity triage rule in acute settings.', relatedConditionIds: ['condition-lateral-ankle-sprain'], referenceIds: ['ref-ottawa-ankle-rule'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'test-slump', title: 'Slump Test', aliases: [], assesses: 'Neural mechanosensitivity', bodyRegionId: 'region-lumbar-spine', targetStructureOrDiagnosis: 'Lumbar radicular pain',
      testPurpose: 'Assesses symptom modulation with neural loading sequence.', patientPosition: 'Seated slump position with cervical/lower limb sequencing.', clinicianAction: ['Progressively add thoracolumbar flexion, knee extension, ankle dorsiflexion.', 'Use cervical release for sensitization check.'],
      positiveFinding: 'Familiar leg-dominant symptoms altered by structural differentiation.', interpretation: 'Supports radicular pain hypothesis with neuro exam findings.', limitations: ['Can provoke non-specific posterior chain discomfort.'],
      diagnosticUtilityNotes: ['Interpret with myotome/reflex/sensory exam.'], evidenceNotes: 'Moderate support in lumbar radicular exam clusters.', relatedConditionIds: ['condition-lumbar-radicular-pain'], referenceIds: ['ref-lbp-cpg-2021'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'test-upper-limb-tension-1', title: 'Upper Limb Neurodynamic Test 1', aliases: ['ULTT1'], assesses: 'Median nerve mechanosensitivity', bodyRegionId: 'region-cervical-spine',
      targetStructureOrDiagnosis: 'Neck pain with radiating symptoms', testPurpose: 'Assesses neural contribution in cervical/upper limb symptoms.', patientPosition: 'Supine.', clinicianAction: ['Shoulder abduction-external rotation, wrist/finger extension, elbow extension with sensitizers.'],
      positiveFinding: 'Familiar symptoms altered by neck side-bending.', interpretation: 'Supports neural mechanosensitivity when paired with neuro deficits/history.', limitations: ['Positive in asymptomatic individuals possible.'],
      diagnosticUtilityNotes: ['Use as part of cluster, not stand-alone.'], evidenceNotes: 'Best interpreted in multi-test framework.', relatedConditionIds: ['condition-neck-mobility-deficits', 'condition-carpal-tunnel-syndrome'], referenceIds: ['ref-neck-cpg-2017'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'test-finkelstein', title: 'Finkelstein Test', aliases: [], assesses: 'First dorsal compartment irritability', bodyRegionId: 'region-hand-wrist', targetStructureOrDiagnosis: 'de Quervain tenosynovitis',
      testPurpose: 'Provokes tendon sheath irritation in thumb-side wrist pain.', patientPosition: 'Sitting with thumb flexed into fist.', clinicianAction: ['Ulnar deviate wrist passively.'],
      positiveFinding: 'Familiar sharp pain over radial styloid.', interpretation: 'Supports de Quervain pattern with local palpation and load behavior.', limitations: ['Can be over-provocative and non-specific.'],
      diagnosticUtilityNotes: ['Use gently and correlate with resisted thumb tests.'], evidenceNotes: 'Common clinical test with limited high-quality accuracy evidence.', relatedConditionIds: ['condition-de-quervains'], referenceIds: ['ref-dequervain'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'test-phalen', title: 'Phalen Test', aliases: ['Wrist flexion test'], assesses: 'Median nerve compression signs', bodyRegionId: 'region-hand-wrist', targetStructureOrDiagnosis: 'Carpal tunnel syndrome',
      testPurpose: 'Provokes paresthesia in median distribution.', patientPosition: 'Seated with sustained wrist flexion.', clinicianAction: ['Hold maximal wrist flexion up to 60 seconds.'], positiveFinding: 'Numbness/tingling in median nerve territory.',
      interpretation: 'Supports CTS pattern with night symptoms and thenar weakness/sensory changes.', limitations: ['Not definitive without broader exam context.'], diagnosticUtilityNotes: ['Pair with symptom map and functional provocation tasks.'],
      evidenceNotes: 'Moderate utility in combination with history/exam cluster.', relatedConditionIds: ['condition-carpal-tunnel-syndrome'], referenceIds: ['ref-carpal-tunnel'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'test-cozen', title: 'Cozen Test', aliases: ["Cozen's test", 'Resisted wrist extension test'], assesses: 'Common extensor tendon provocation', bodyRegionId: 'region-elbow-forearm',
      targetStructureOrDiagnosis: 'Lateral elbow tendinopathy', testPurpose: 'Symptom-provocation test used alongside history and local exam for lateral elbow tendinopathy.',
      patientPosition: 'Seated with elbow flexed, forearm pronated, and hand in a relaxed fist.', clinicianAction: ['Stabilize the elbow as needed.', 'Ask the patient to extend and radially deviate the wrist against resistance.'],
      positiveFinding: 'Familiar lateral elbow pain reproduced near the common extensor origin.', interpretation: 'Supports a lateral elbow tendinopathy hypothesis when the pain location and load history match.',
      limitations: ['Not specific as a stand-alone diagnosis.', 'High irritability can make many resisted gripping tasks painful.'], diagnosticUtilityNotes: ['Pair with palpation, grip testing, and radial tunnel/cervical screening.', 'Use location and symptom behavior, not a binary positive/negative result alone.'],
      evidenceNotes: 'Primarily a symptom-provocation test; interpret within the wider lateral elbow exam.', relatedConditionIds: ['condition-lateral-epicondylalgia'], referenceIds: [], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'test-maudsley', title: 'Maudsley Test', aliases: ["Maudsley's test", 'Middle finger extension test'], assesses: 'Extensor digitorum provocation', bodyRegionId: 'region-elbow-forearm',
      targetStructureOrDiagnosis: 'Lateral elbow tendinopathy', testPurpose: 'Adjunct provocation test that biases finger extensor loading in lateral elbow presentations.',
      patientPosition: 'Seated with elbow extended or slightly flexed, forearm pronated, and fingers relaxed.', clinicianAction: ['Stabilize the hand.', 'Resist extension of the middle finger while monitoring lateral elbow pain.'],
      positiveFinding: 'Familiar lateral elbow pain reproduced with resisted middle-finger extension.', interpretation: 'Adds support for a lateral elbow tendinopathy hypothesis when paired with local tenderness and load-provoked symptoms.',
      limitations: ['Provocation can reflect radial tunnel irritation as well as tendon-related pain.', 'Not validated as a stand-alone rule-in test.'], diagnosticUtilityNotes: ['Use after symptom map and neurological screen.', 'Compare with Cozen or gripping response rather than relying on one provocative sign.'],
      evidenceNotes: 'Useful as a focused provocation test, but diagnostic certainty still comes from the full exam cluster.', relatedConditionIds: ['condition-lateral-epicondylalgia'], referenceIds: [], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'test-tinel-carpal-tunnel', title: 'Tinel Sign at Carpal Tunnel', aliases: ['Tinel at carpal tunnel', "Tinel's sign at carpal tunnel", 'Carpal tunnel Tinel sign'], assesses: 'Median nerve irritability at the carpal tunnel', bodyRegionId: 'region-hand-wrist',
      targetStructureOrDiagnosis: 'Carpal tunnel syndrome', testPurpose: 'Adjunct symptom-provocation test used with history, sensory findings, and function in suspected carpal tunnel syndrome.',
      patientPosition: 'Seated with forearm supinated and wrist relaxed.', clinicianAction: ['Palpate the carpal tunnel region.', 'Tap lightly over the median nerve at the volar wrist.'],
      positiveFinding: 'Tingling or electric symptoms reproduced into the median nerve distribution.', interpretation: 'Supports CTS when the symptom distribution and clinical pattern are otherwise consistent.',
      limitations: ['Sensitivity and specificity vary across populations.', 'A negative result does not rule out CTS.'], diagnosticUtilityNotes: ['Interpret alongside nocturnal symptoms, sensory change, thenar status, and Phalen response.', 'Do not overcall isolated local discomfort without neural symptoms.'],
      evidenceNotes: 'Adjunctive provocative test only; best used within a broader carpal tunnel cluster.', relatedConditionIds: ['condition-carpal-tunnel-syndrome'], referenceIds: ['ref-carpal-tunnel'], lastReviewed: REVIEW_METADATA,
    },
  ],
  treatments: [
    {
      id: 'tx-education-load-modification', title: 'Education + Load Modification', aliases: ['Activity pacing', 'Activity modification and graded return', 'Task ergonomics and graded exposure', 'Education and reassurance', 'Graded activity and walking tolerance'],
      whatItIs: 'Patient-specific pacing, graded exposure, and recovery expectation setting.',
      whenToUse: ['Any irritable phase.', 'When fear or overprotection is limiting recovery.'],
      whenNotToOveruse: ['Avoid indefinite unloading once symptoms settle.'],
      stageRelevance: ['acute-irritable', 'subacute', 'chronic'], indications: ['Pain flare volatility.', 'Recent spike in workload.'],
      contraindicationsPrecautions: ['Screen red flags before conservative-only plan.'],
      practicalNotes: ['Use simple pain-monitoring rule with 24-hour response check.', 'Tie advice to patient priorities (work/sport/sleep).'],
      evidenceSummary: 'Widely supported first-line component across outpatient MSK care.', referenceIds: ['ref-lbp-cpg-2021', 'ref-rcsp-cpg-2022'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'tx-progressive-resistance-exercise', title: 'Progressive Resistance Exercise', aliases: ['Progressive loading', 'Tendon load progression', 'Load-managed rotator cuff strengthening', 'Quadriceps and hip strengthening', 'Progressive hip abductor and extensor loading'],
      whatItIs: 'Structured strength progression with symptom-informed dosage.', whenToUse: ['Subacute and chronic phases.', 'Deconditioning and force deficits.'],
      whenNotToOveruse: ['Avoid abrupt dose jumps after flares.'], stageRelevance: ['subacute', 'chronic', 'post-op-late', 'return-to-sport'],
      indications: ['Functional weakness.', 'Need for return-to-work/sport loading capacity.'], contraindicationsPrecautions: ['Respect post-op restrictions and severe irritability.'],
      practicalNotes: ['Progress one variable at a time: load, ROM, speed, complexity.', 'Track performance and next-day response.'], evidenceSummary: 'Strong support versus passive-only care in many MSK conditions.', referenceIds: ['ref-acsm-loading'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'tx-neuromuscular-balance-retraining', title: 'Neuromuscular + Balance Retraining', aliases: ['Sensorimotor retraining', 'Scapular motor control interventions', 'Neuromuscular retraining'], whatItIs: 'Control, proprioception, and dynamic stability retraining.',
      whenToUse: ['Ankle sprain rehab.', 'Knee and return-to-sport phases.'], whenNotToOveruse: ['Do not start with highly unstable tasks before base strength.'],
      stageRelevance: ['subacute', 'chronic', 'return-to-sport'], indications: ['Recurrent giving-way.', 'Poor single-leg control.'], contraindicationsPrecautions: ['Adjust for fall risk.'],
      practicalNotes: ['Progress predictable to reactive tasks.', 'Integrate with regional strength work.'], evidenceSummary: 'Supported for reducing recurrent ankle instability risk.', referenceIds: ['ref-ankle-cpg-2021'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'tx-manual-therapy-adjunct', title: 'Manual Therapy (Adjunct)', aliases: ['Joint/soft tissue manual therapy', 'Manual therapy adjuncts for pain modulation', 'Manual therapy where appropriate'], whatItIs: 'Short-term symptom modulation paired with active care.',
      whenToUse: ['Pain-limited movement preventing exercise start.', 'Cervical mobility deficits and headache presentations.'], whenNotToOveruse: ['Do not use as sole long-term intervention.'],
      stageRelevance: ['acute-irritable', 'subacute'], indications: ['ROM restriction with pain guarding.'], contraindicationsPrecautions: ['Screen vascular/neuro risk in cervical region.'],
      practicalNotes: ['Use to create a movement window, then load.', 'Reassess immediate and 24-hour response.'], evidenceSummary: 'Best effect as adjunct to exercise and education.', referenceIds: ['ref-neck-cpg-2017', 'ref-lbp-cpg-2021'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'tx-bracing-taping', title: 'Bracing/Taping Support', aliases: ['External support', 'Splinting / orthotic support as indicated'], whatItIs: 'Short-term support to reduce irritability and improve confidence.',
      whenToUse: ['Acute ankle sprain.', 'Early patellofemoral symptom management with load progression.'], whenNotToOveruse: ['Avoid creating long-term dependency.'],
      stageRelevance: ['acute-irritable', 'subacute'], indications: ['Pain during necessary daily loading.'], contraindicationsPrecautions: ['Skin irritation/allergy and circulation issues.'],
      practicalNotes: ['Pair with strengthening and movement retraining.', 'Set planned weaning timeline.'], evidenceSummary: 'Can provide short-term symptom and confidence benefit when combined with rehab.', referenceIds: ['ref-ankle-cpg-2021', 'ref-pfp-cpg-2019'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'tx-nerve-mobility', title: 'Neural Mobility Intervention', aliases: ['Nerve sliders/tensioners', 'Nerve-gliding and interface management'], whatItIs: 'Graded neurodynamic movement to reduce mechanosensitivity.',
      whenToUse: ['Lumbar radicular pain with neural signs.', 'Cervical/upper-limb neural irritability.'], whenNotToOveruse: ['Avoid aggressive tensioning in highly irritable acute states.'],
      stageRelevance: ['acute-irritable', 'subacute', 'chronic'], indications: ['Reproducible neurodynamic symptoms.'], contraindicationsPrecautions: ['Progress slowly with symptom monitoring.'],
      practicalNotes: ['Prefer sliders first.', 'Dose low and frequent early.'], evidenceSummary: 'Moderate evidence as part of multimodal care for neural mechanosensitivity.', referenceIds: ['ref-lbp-cpg-2021', 'ref-neck-cpg-2017'], lastReviewed: REVIEW_METADATA,
    },
  ],
  exerciseProgressions: [
    {
      id: 'ex-shoulder-cuff-loading', title: 'Rotator Cuff Loading Progression', aliases: ['Isometric to isotonic cuff ladder'],
      targetConditionIds: ['condition-rcrsp', 'condition-shoulder-instability'], targetTissuesFunctions: ['Cuff force capacity', 'Scapulohumeral control'], stage: 'subacute',
      entryCriteria: ['Pain settles within 24 hours after light loading.', 'Able to elevate shoulder to at least ~90°.'], dosageSuggestions: ['2-4 sessions/week, 3-4 sets of 8-12 reps after isometric phase.'],
      commonCompensations: ['Upper-trap dominance.', 'Trunk side-bend substitution.'], progressionOptions: ['Increase lever arm and overhead arc.', 'Add perturbation or speed intent later.'], regressionOptions: ['Shorter lever and reduced range.'],
      criteriaToAdvance: ['No volatility increase for 1 week.', 'Improved task tolerance overhead.'], returnToFunctionRelevance: 'Supports return to overhead work and sport.', evidenceNotes: 'Consistent loading is central for shoulder outcomes.', referenceIds: ['ref-rcsp-cpg-2022'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'ex-knee-pfp-stepdown', title: 'PFP Progression: Sit-to-Stand to Step-Down', aliases: ['Anterior knee pain loading ladder'],
      targetConditionIds: ['condition-patellofemoral-pain'], targetTissuesFunctions: ['Quadriceps capacity', 'Hip/knee movement control'], stage: 'subacute',
      entryCriteria: ['Pain manageable with bodyweight squat.', 'No reactive swelling.'], dosageSuggestions: ['2-3 sessions/week with controlled tempo and pain-monitoring model.'],
      commonCompensations: ['Dynamic valgus collapse.', 'Rapid uncontrolled descent.'], progressionOptions: ['Increase depth and external load.', 'Add single-leg decline/split squat variants.'], regressionOptions: ['Use box height and support.'],
      criteriaToAdvance: ['Improved step tolerance and stairs function.', 'Symptoms remain acceptable by next day.'], returnToFunctionRelevance: 'Improves stairs, running, and squat tolerance.', evidenceNotes: 'Hip+knee strengthening supported in PFP.', referenceIds: ['ref-pfp-cpg-2019'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'ex-acl-strength-plyo', title: 'ACL Rehab Progression: Strength to Plyometric Prep', aliases: ['ACL late-stage continuum'],
      targetConditionIds: ['condition-acl-rehab-overview'], targetTissuesFunctions: ['Quadriceps/hamstring strength', 'Landing control'], stage: 'return-to-sport',
      entryCriteria: ['Stable knee with minimal effusion.', 'Foundational single-leg strength present.'], dosageSuggestions: ['Strength 2-3x/week plus graded low-to-high plyometric exposures.'],
      commonCompensations: ['Stiff-knee landing.', 'Asymmetric loading toward uninvolved limb.'], progressionOptions: ['Add deceleration and directional change drills.', 'Integrate sport constraints.'], regressionOptions: ['Reduce depth/impact and speed.'],
      criteriaToAdvance: ['Pass agreed performance and readiness benchmarks.', 'No reactive swelling after higher-load sessions.'], returnToFunctionRelevance: 'Bridges rehab to return-to-sport tasks.', evidenceNotes: 'Editorial follow-up: add clearer benchmark citations.', referenceIds: ['ref-lachman-evidence'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'ex-ankle-calf-balance', title: 'Ankle Progression: Calf Raise to Hop Control', aliases: ['Ankle force-control ladder'],
      targetConditionIds: ['condition-lateral-ankle-sprain', 'condition-achilles-tendinopathy', 'condition-plantar-heel-pain'], targetTissuesFunctions: ['Plantarflexor strength', 'Single-leg control'], stage: 'subacute',
      entryCriteria: ['Pain allows full weight-bearing gait.', 'Can perform bilateral heel raises.'], dosageSuggestions: ['3-4 sets across strength and control drills, 2-4 days/week.'], commonCompensations: ['Load shift away from symptomatic side.'],
      progressionOptions: ['Single-leg raises, then hops and directional drills.', 'Add external load and speed intent.'], regressionOptions: ['Supported bilateral raises and reduced range.'],
      criteriaToAdvance: ['Symmetry improving on single-leg calf endurance.', 'No increased swelling or morning pain spike.'], returnToFunctionRelevance: 'Essential for gait, stairs, running, jumping.', evidenceNotes: 'Strong practical transfer across ankle-foot conditions.', referenceIds: ['ref-ankle-cpg-2021'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'ex-lumbar-graded-activity', title: 'Lumbar Progression: Symptom-Guided Trunk + Hip Loading', aliases: ['LBP graded activity ladder'],
      targetConditionIds: ['condition-nonspecific-low-back-pain', 'condition-lumbar-radicular-pain'], targetTissuesFunctions: ['Trunk endurance', 'Load confidence'], stage: 'subacute',
      entryCriteria: ['Severe pain volatility settling.', 'Able to perform low-load movement practice.'], dosageSuggestions: ['Frequent low-dose movement with progressive strengthening 2-3x/week.'],
      commonCompensations: ['Fear-driven guarding and breath-holding.', 'Rapid load escalation after good day.'], progressionOptions: ['Increase hinge/squat/carry demands.', 'Add work/sport simulation drills.'], regressionOptions: ['Shorter bouts and smaller ranges.'],
      criteriaToAdvance: ['Function improves despite some pain variability.', 'Higher load tolerated with predictable recovery.'], returnToFunctionRelevance: 'Targets lifting, prolonged postures, and work tolerance.', evidenceNotes: 'Guidelines support exercise and activity continuation.', referenceIds: ['ref-lbp-cpg-2021'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'ex-neck-mobility-endurance', title: 'Neck Progression: Mobility to Deep Neck Flexor Endurance', aliases: ['Cervical mobility-deficit progression'],
      targetConditionIds: ['condition-neck-mobility-deficits', 'condition-cervicogenic-headache'], targetTissuesFunctions: ['Cervical mobility', 'Deep neck flexor/endurance control'], stage: 'subacute',
      entryCriteria: ['Irritability controlled enough for repeated movement.', 'No red-flag neurovascular signs.'], dosageSuggestions: ['Daily mobility + 2-4x/week endurance and scapular exercises.'],
      commonCompensations: ['Superficial neck overuse.', 'Thoracic stiffness not addressed.'], progressionOptions: ['Increase hold duration and functional posture tasks.', 'Add upper-quarter endurance demands.'], regressionOptions: ['Lower hold intensity and partial ROM.'],
      criteriaToAdvance: ['Headache/neck pain frequency trending down.', 'Improved rotation and sustained posture tolerance.'], returnToFunctionRelevance: 'Improves desk, driving, and overhead tolerance.', evidenceNotes: 'Good support for exercise + manual therapy combination.', referenceIds: ['ref-neck-cpg-2017'], lastReviewed: REVIEW_METADATA,
    },
  ],
  outcomeMeasures: [
    {
      id: 'om-spadi', title: 'SPADI', aliases: ['Shoulder Pain and Disability Index'], bodyRegionId: 'region-shoulder', population: 'Adults with shoulder pain.',
      conditionRelevanceConditionIds: ['condition-rcrsp', 'condition-adhesive-capsulitis', 'condition-shoulder-instability', 'condition-ac-joint-sprain'],
      administration: ['Self-report 13 items.'], scoring: ['Pain + disability subscales; higher is worse.'], mcidMdc: ['MCID varies by setting; often around 8-13 points.'], interpretation: ['Use with task-level goals and irritability pattern.'], referenceIds: ['ref-outcome-measures'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'om-quickdash', title: 'QuickDASH', aliases: ['Quick Disabilities of Arm, Shoulder and Hand'], bodyRegionId: 'region-hand-wrist', population: 'Upper-limb MSK conditions.',
      conditionRelevanceConditionIds: ['condition-lateral-epicondylalgia', 'condition-de-quervains', 'condition-carpal-tunnel-syndrome'], administration: ['11-item self-report.'], scoring: ['0-100 scale; higher is worse.'],
      mcidMdc: ['Often around 8-15 points depending on population.'], interpretation: ['Interpret with job/sport task changes.'], referenceIds: ['ref-outcome-measures'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'om-prtee', title: 'PRTEE', aliases: ['Patient-Rated Tennis Elbow Evaluation'], bodyRegionId: 'region-elbow-forearm', population: 'Adults with lateral elbow tendinopathy / epicondylalgia.',
      conditionRelevanceConditionIds: ['condition-lateral-epicondylalgia'], administration: ['15-item self-report questionnaire covering pain and functional difficulty.'],
      scoring: ['0-100 total score; higher scores reflect greater pain and disability.'], mcidMdc: ['Verify threshold values against current PRTEE psychometric sources before formal reporting.'],
      interpretation: ['Useful for tracking lateral elbow pain severity and task-related limitation over time.', 'Pair PROM change with grip and load-tolerance measures.'], referenceIds: ['ref-outcome-measures'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'om-bctq', title: 'Boston Carpal Tunnel Questionnaire', aliases: ['BCTQ', 'Boston Questionnaire', 'Levine Questionnaire'], bodyRegionId: 'region-hand-wrist', population: 'Adults with suspected or confirmed carpal tunnel syndrome.',
      conditionRelevanceConditionIds: ['condition-carpal-tunnel-syndrome'], administration: ['Self-report symptom severity and functional status scales.'],
      scoring: ['Symptom and function subscales are scored separately; higher scores indicate worse status.'], mcidMdc: ['Verify condition-specific thresholds during evidence review before using for formal audit reporting.'],
      interpretation: ['Helpful for monitoring nocturnal paresthesia burden and hand-function change in CTS.', 'Use alongside sensory and motor reassessment rather than PROM change alone.'], referenceIds: ['ref-outcome-measures'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'om-koos-jr', title: 'KOOS-JR', aliases: [], bodyRegionId: 'region-knee', population: 'Knee pain and OA populations.',
      conditionRelevanceConditionIds: ['condition-knee-oa', 'condition-meniscal-irritation', 'condition-acl-rehab-overview'], administration: ['7-item self-report.'], scoring: ['Normalized 0-100 score.'],
      mcidMdc: ['Use local benchmarks; variability across populations.'], interpretation: ['Track at baseline and at key rehab milestones.'], referenceIds: ['ref-outcome-measures'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'om-lefs', title: 'LEFS', aliases: ['Lower Extremity Functional Scale'], bodyRegionId: 'region-knee', population: 'Lower-extremity MSK presentations.',
      conditionRelevanceConditionIds: ['condition-patellofemoral-pain', 'condition-mcl-sprain', 'condition-lateral-ankle-sprain', 'condition-achilles-tendinopathy', 'condition-plantar-heel-pain'],
      administration: ['20-item questionnaire.'], scoring: ['0-80, higher is better function.'], mcidMdc: ['MCID commonly around 9 points.'], interpretation: ['Useful for broad lower-limb progression tracking.'], referenceIds: ['ref-outcome-measures'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'om-odi', title: 'Oswestry Disability Index', aliases: ['ODI'], bodyRegionId: 'region-lumbar-spine', population: 'Low back pain populations.',
      conditionRelevanceConditionIds: ['condition-nonspecific-low-back-pain', 'condition-lumbar-radicular-pain'], administration: ['10 domains self-report.'], scoring: ['0-100% disability.'],
      mcidMdc: ['Commonly around 10 points; vary by baseline severity.'], interpretation: ['Use with activity and work participation outcomes.'], referenceIds: ['ref-outcome-measures'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'om-ndi', title: 'Neck Disability Index', aliases: ['NDI'], bodyRegionId: 'region-cervical-spine', population: 'Neck pain and headache presentations.',
      conditionRelevanceConditionIds: ['condition-neck-mobility-deficits', 'condition-cervicogenic-headache'], administration: ['10-item self-report.'], scoring: ['0-50 raw, often converted to %.'],
      mcidMdc: ['MCID often around 5-7 points raw scale.'], interpretation: ['Track with headache frequency and cervical ROM.'], referenceIds: ['ref-outcome-measures'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'om-psfs', title: 'Patient-Specific Functional Scale', aliases: ['PSFS'], bodyRegionId: 'region-lumbar-spine', population: 'Any outpatient MSK presentation.',
      conditionRelevanceConditionIds: [
        'condition-rcrsp', 'condition-adhesive-capsulitis', 'condition-shoulder-instability', 'condition-ac-joint-sprain',
        'condition-patellofemoral-pain', 'condition-meniscal-irritation', 'condition-mcl-sprain', 'condition-knee-oa', 'condition-acl-rehab-overview',
        'condition-lateral-ankle-sprain', 'condition-achilles-tendinopathy', 'condition-plantar-heel-pain',
        'condition-nonspecific-low-back-pain', 'condition-lumbar-radicular-pain', 'condition-neck-mobility-deficits', 'condition-cervicogenic-headache',
        'condition-lateral-epicondylalgia', 'condition-de-quervains', 'condition-carpal-tunnel-syndrome',
      ],
      administration: ['Patient rates 3-5 priority activities 0-10.'], scoring: ['Average score; higher is better function.'], mcidMdc: ['Often meaningful change around 2 points.'],
      interpretation: ['High clinical utility for individualized care planning.'], referenceIds: ['ref-outcome-measures'], lastReviewed: REVIEW_METADATA,
    },
  ],
  redFlags: [
    {
      id: 'redflag-cancer-systemic', title: 'Potential Cancer/Systemic Disease Pattern', aliases: ['Unexplained weight loss + non-mechanical pain'],
      scenario: 'Persistent non-mechanical pain, night pain, weight loss, and constitutional symptoms.', whyItMatters: 'May indicate serious systemic pathology.',
      whatToAsk: ['Cancer history?', 'Unintentional weight loss?', 'Persistent fever/night sweats/fatigue?'], whatToLookFor: ['Pain not eased by position or rest.', 'Progressive neurological decline.'],
      escalationPathway: ['Stop routine rehab-only plan.', 'Urgent GP/medical referral and safety-net instructions.'], referralUrgency: 'urgent-24h', referenceIds: ['ref-red-flag-cancer'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'redflag-cauda-equina', title: 'Suspected Cauda Equina Syndrome', aliases: [], scenario: 'Severe back pain with new saddle anesthesia, bladder/bowel changes, or bilateral progressive leg symptoms.',
      whyItMatters: 'Time-sensitive neurological emergency.', whatToAsk: ['New urinary retention/incontinence?', 'Saddle sensory changes?', 'Rapid bilateral weakness?'],
      whatToLookFor: ['Widespread/progressive neuro deficits.', 'Severe gait compromise.'], escalationPathway: ['Emergency referral immediately.', 'Document exact symptom onset and actions.'], referralUrgency: 'immediate-emergency',
      referenceIds: ['ref-lbp-cpg-2021'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'redflag-fracture-acute-trauma', title: 'Possible Fracture After Trauma', aliases: [], scenario: 'Acute trauma with inability to weight-bear/use limb and focal bony tenderness.', whyItMatters: 'Missed fracture can worsen outcomes.',
      whatToAsk: ['Mechanism and immediate function post-injury?', 'Prior fracture or osteoporosis risk?'], whatToLookFor: ['Point bony tenderness.', 'Gross swelling/deformity.'],
      escalationPathway: ['Use region-specific decision rules.', 'Refer for urgent imaging when indicated.'], referralUrgency: 'urgent-24h', referenceIds: ['ref-ottawa-ankle-rule'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'redflag-progressive-neuro-deficit', title: 'Progressive Neurological Deficit', aliases: [], scenario: 'Worsening motor weakness, reflex changes, or sensory loss over days to weeks.',
      whyItMatters: 'May indicate compressive or central neurological pathology.', whatToAsk: ['Progression speed?', 'Bilateral symptoms?', 'Hand dexterity or gait decline?'],
      whatToLookFor: ['Myotomal strength deterioration.', 'Upper motor neuron signs when relevant.'], escalationPathway: ['Expedited medical referral.', 'Safety-net and monitor for emergency features.'],
      referralUrgency: 'expedited-1-2-weeks', referenceIds: ['ref-neck-cpg-2017', 'ref-lbp-cpg-2021'], lastReviewed: REVIEW_METADATA,
    },
  ],
  conditions: [
    {
      id: 'condition-rcrsp', title: 'Rotator Cuff-Related Shoulder Pain', aliases: ['RCRSP', 'Subacromial shoulder pain', 'Subacromial pain syndrome'], bodyRegionId: 'region-shoulder',
      clinicalSnapshot: 'Load-sensitive shoulder pain with overhead intolerance and painful arc features.',
      typicalPattern: ['Pain with overhead/reaching tasks.', 'Night pain when lying on involved side is common.'],
      commonSubjectiveClues: ['Recent workload spike.', 'Pain eases with relative rest but recurs on reload.'],
      objectiveExamPriorities: ['Irritability profile and asterisk signs.', 'Resisted cuff testing and scapulohumeral control.', 'Exclude cervical/stiff shoulder mimics.'],
      keyDifferentialConditionIds: ['condition-adhesive-capsulitis', 'condition-ac-joint-sprain'], specialTestIds: ['test-hawkins-kennedy'],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Reduce volatility.', 'Maintain safe shoulder movement.'], treatmentIds: ['tx-education-load-modification', 'tx-manual-therapy-adjunct'], progressionFocus: ['Short-lever isometrics', 'Sleep/load modification'], reassessmentPriorities: ['Night pain trend', '24-hour flare response'] },
        { stage: 'subacute', goals: ['Restore cuff force and overhead tolerance.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Cuff and scapular loading progression'], reassessmentPriorities: ['Task-specific tolerance', 'SPADI/PSFS trend'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-shoulder-cuff-loading'], rationale: 'Builds cuff capacity for ADLs and overhead function.' }],
      healingRecoveryTimeline: ['Common pattern: early calming over weeks, then progressive loading over subsequent weeks to months.'],
      redFlagTopicIds: ['redflag-cancer-systemic'], commonMistakesPitfalls: ['Over-reliance on single special test.', 'Progressing load despite >24-hour reactive flare.'],
      evidenceSummary: 'Good evidence for education + progressive exercise as core care; passive care is adjunctive.', referenceIds: ['ref-rcsp-cpg-2022'], evidenceStrengthTags: ['high'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-adhesive-capsulitis', title: 'Adhesive Capsulitis', aliases: ['Frozen shoulder'], bodyRegionId: 'region-shoulder',
      clinicalSnapshot: 'Painful stiff shoulder with marked global ROM loss, especially external rotation.', typicalPattern: ['Gradual onset and prolonged recovery arc.', 'Night pain and dressing/grooming limitation are common.'],
      commonSubjectiveClues: ['Progressive stiffness over months.', 'Disproportionate movement restriction relative to weakness.'], objectiveExamPriorities: ['Assess passive and active capsular pattern restrictions.', 'Differentiate from RCRSP and severe OA pathology.'],
      keyDifferentialConditionIds: ['condition-rcrsp'], specialTestIds: [],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Reduce pain irritability.', 'Protect sleep and basic function.'], treatmentIds: ['tx-education-load-modification', 'tx-manual-therapy-adjunct'], progressionFocus: ['Gentle mobility in tolerated range'], reassessmentPriorities: ['Night pain', 'ROM irritability'] },
        { stage: 'subacute', goals: ['Progress ROM and shoulder function.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Mobility + strengthening blend'], reassessmentPriorities: ['SPADI/PSFS', 'ROM trend over weeks not days'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-shoulder-cuff-loading'], rationale: 'Supports mobility-to-strength transition once irritability settles.' }],
      healingRecoveryTimeline: ['Common pattern is months to longer-term recovery; timeline varies substantially across individuals.'], redFlagTopicIds: ['redflag-cancer-systemic'],
      commonMistakesPitfalls: ['Aggressive stretching in highly irritable phase.', 'Setting rigid prognosis timelines.'], evidenceSummary: 'Staged management is recommended; evidence quality for specific protocols remains mixed.', referenceIds: ['ref-rcsp-cpg-2022'], evidenceStrengthTags: ['moderate'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-shoulder-instability', title: 'Shoulder Instability (Traumatic/Recurrent)', aliases: ['Anterior instability', 'Shoulder instability'], bodyRegionId: 'region-shoulder',
      clinicalSnapshot: 'Apprehension and giving-way episodes in vulnerable positions, often after trauma.', typicalPattern: ['Symptoms in abduction-external rotation.', 'Recurrent episodes in younger active populations are common.'],
      commonSubjectiveClues: ['Sensation shoulder may slip out.', 'History of dislocation/subluxation event.'], objectiveExamPriorities: ['Apprehension/relocation response.', 'Strength and dynamic control deficits.', 'Neurovascular screen after traumatic event.'],
      keyDifferentialConditionIds: ['condition-rcrsp'], specialTestIds: ['test-apprehension-relocation'],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Settle pain and protect instability positions.'], treatmentIds: ['tx-education-load-modification', 'tx-bracing-taping'], progressionFocus: ['Protected ROM and early cuff activation'], reassessmentPriorities: ['Apprehension threshold', 'Functional confidence'] },
        { stage: 'return-to-sport', goals: ['Restore dynamic stability for overhead/contact demands.'], treatmentIds: ['tx-progressive-resistance-exercise', 'tx-neuromuscular-balance-retraining'], progressionFocus: ['Reactive cuff/scap control and sport constraints'], reassessmentPriorities: ['Recurrence signs', 'Task-specific confidence'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-shoulder-cuff-loading'], rationale: 'Builds rotator cuff and scapular control to improve shoulder stability tolerance.' }],
      healingRecoveryTimeline: ['Course varies by recurrence risk and sport demands; staged exposure is usually required.'], redFlagTopicIds: ['redflag-fracture-acute-trauma', 'redflag-progressive-neuro-deficit'],
      commonMistakesPitfalls: ['Returning to high-risk positions too early.', 'Ignoring fear/apprehension despite strength gains.'], evidenceSummary: 'Rehab focuses on strength, control, and graded exposure; surgical referral may be appropriate in recurrent instability.',
      referenceIds: ['ref-acsm-loading'], evidenceStrengthTags: ['moderate', 'expert-consensus'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-ac-joint-sprain', title: 'Acromioclavicular (AC) Joint Sprain', aliases: ['AC sprain'], bodyRegionId: 'region-shoulder',
      clinicalSnapshot: 'Superior shoulder pain after direct impact or fall onto shoulder.', typicalPattern: ['Pain with cross-body adduction and pressing tasks.'],
      commonSubjectiveClues: ['Localized tenderness over AC joint.', 'Mechanism often direct trauma onto lateral shoulder.'], objectiveExamPriorities: ['Palpation tenderness and deformity screen.', 'Rule out fracture/severe separation.'],
      keyDifferentialConditionIds: ['condition-rcrsp'], specialTestIds: [],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Control pain and protect tissue.'], treatmentIds: ['tx-education-load-modification', 'tx-bracing-taping'], progressionFocus: ['Range as tolerated and symptom control'], reassessmentPriorities: ['Pain at rest', 'Night comfort'] },
        { stage: 'subacute', goals: ['Restore pressing and overhead tolerance.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Scapular and shoulder loading progression'], reassessmentPriorities: ['Functional pressing tasks', 'SPADI trend'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-shoulder-cuff-loading'], rationale: 'Rebuilds shoulder load tolerance after acute irritability settles.' }],
      healingRecoveryTimeline: ['Milder sprains often recover over weeks; higher-grade injuries need longer staged progression and specialist input.'], redFlagTopicIds: ['redflag-fracture-acute-trauma'],
      commonMistakesPitfalls: ['Missing higher-grade deformity and fracture signs.', 'Early high-load horizontal adduction.'], evidenceSummary: 'Good clinical utility for staged loading; evidence base is moderate and mechanism-driven.', referenceIds: ['ref-acsm-loading'], evidenceStrengthTags: ['moderate', 'expert-consensus'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-patellofemoral-pain', title: 'Patellofemoral Pain', aliases: ['PFP', 'Anterior knee pain'], bodyRegionId: 'region-knee', clinicalSnapshot: 'Retropatellar/peripatellar pain with stairs, squatting, and running loads.',
      typicalPattern: ['Pain with knee-flexion loaded tasks.', 'Symptoms often fluctuate with training volume.'], commonSubjectiveClues: ['Pain with prolonged sitting/stairs.', 'Load spikes preceding flare.'], objectiveExamPriorities: ['Movement quality in squat/step tasks.', 'Hip and knee strength profile.', 'Irritability-guided loading threshold.'],
      keyDifferentialConditionIds: ['condition-meniscal-irritation', 'condition-knee-oa'], specialTestIds: [],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Calm symptoms while keeping activity.'], treatmentIds: ['tx-education-load-modification', 'tx-bracing-taping'], progressionFocus: ['Modify depth/volume and maintain movement'], reassessmentPriorities: ['24-hour pain response', 'stairs tolerance'] },
        { stage: 'subacute', goals: ['Improve lower-limb strength and movement control.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Hip + knee strengthening continuum'], reassessmentPriorities: ['LEFS/PSFS', 'step-down quality'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-knee-pfp-stepdown'], rationale: 'Progressively reloads patellofemoral system with movement control emphasis.' }],
      healingRecoveryTimeline: ['Common pattern is gradual improvement over weeks to months with consistent loading approach.'], redFlagTopicIds: ['redflag-fracture-acute-trauma'],
      commonMistakesPitfalls: ['Over-focusing on passive modalities.', 'Rapid return to high-volume running without capacity build.'], evidenceSummary: 'Strong support for exercise-centered care, especially hip and knee strengthening with load management.',
      referenceIds: ['ref-pfp-cpg-2019'], evidenceStrengthTags: ['high'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-meniscal-irritation', title: 'Meniscal Irritation / Meniscal Injury Overview', aliases: ['Meniscal pathology overview', 'Meniscal pathology'], bodyRegionId: 'region-knee',
      clinicalSnapshot: 'Joint-line dominant knee pain with possible catching/locking symptoms after twist or compression load.', typicalPattern: ['Mechanical symptoms can occur but are variably present.', 'Degenerative patterns may present without clear trauma.'],
      commonSubjectiveClues: ['Twisting mechanism or gradual degenerative onset.', 'Pain with deep flexion and pivoting.'], objectiveExamPriorities: ['Effusion and range assessment.', 'Mechanical symptom profile and load tolerance.', 'Meniscal cluster tests as tolerated.'],
      keyDifferentialConditionIds: ['condition-patellofemoral-pain', 'condition-knee-oa', 'condition-acl-rehab-overview'], specialTestIds: ['test-thessaly'],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Reduce reactive swelling and pain.', 'Maintain safe mobility.'], treatmentIds: ['tx-education-load-modification'], progressionFocus: ['Range and gait normalization'], reassessmentPriorities: ['Effusion trend', 'locking/catching behavior'] },
        { stage: 'subacute', goals: ['Restore squat and rotational load tolerance.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Quadriceps/hip progression and functional loading'], reassessmentPriorities: ['KOOS-JR/LEFS', 'task tolerance'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-knee-pfp-stepdown'], rationale: 'Builds lower-limb capacity for functional knee loading progression.' }],
      healingRecoveryTimeline: ['Recovery varies widely by tear type, irritability, age, and operative/non-operative pathway.'], redFlagTopicIds: ['redflag-fracture-acute-trauma', 'redflag-progressive-neuro-deficit'],
      commonMistakesPitfalls: ['Assuming all meniscal findings require surgery.', 'Using one provocative test as definitive diagnosis.'], evidenceSummary: 'Many cases improve with conservative, exercise-led care; escalation based on persistent mechanical block, instability, or non-response.',
      referenceIds: ['ref-knee-oa-cpg-2021'], evidenceStrengthTags: ['moderate'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-mcl-sprain', title: 'MCL Sprain', aliases: ['Medial collateral ligament sprain'], bodyRegionId: 'region-knee',
      clinicalSnapshot: 'Medial knee pain and valgus-provoked symptoms after lateral force or twist.', typicalPattern: ['Localized medial tenderness with valgus stress pain.', 'Most grade I-II presentations progress well with rehab.'],
      commonSubjectiveClues: ['Mechanism involving valgus stress.', 'Pain with pivoting and side-step.'], objectiveExamPriorities: ['Valgus stress at 30° and 0°.', 'Effusion and gait status.', 'Screen concomitant ACL/meniscal signs.'],
      keyDifferentialConditionIds: ['condition-meniscal-irritation', 'condition-acl-rehab-overview'], specialTestIds: ['test-valgus-stress-30'],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Protect ligament and settle symptoms.'], treatmentIds: ['tx-education-load-modification', 'tx-bracing-taping'], progressionFocus: ['Pain-limited ROM and gait normalization'], reassessmentPriorities: ['Medial tenderness', 'walking tolerance'] },
        { stage: 'subacute', goals: ['Restore frontal-plane knee control and strength.'], treatmentIds: ['tx-progressive-resistance-exercise', 'tx-neuromuscular-balance-retraining'], progressionFocus: ['Single-leg control and directional drills'], reassessmentPriorities: ['LEFS', 'valgus control quality'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-knee-pfp-stepdown'], rationale: 'Provides controlled frontal-plane challenge progression.' }],
      healingRecoveryTimeline: ['Grade I-II often improve over weeks; higher-grade injuries may require longer protection and specialist review.'], redFlagTopicIds: ['redflag-fracture-acute-trauma'],
      commonMistakesPitfalls: ['Skipping combined-ligament screen.', 'Early high-demand cutting before control returns.'], evidenceSummary: 'Best outcomes from staged loading and control retraining matched to tissue irritability.', referenceIds: ['ref-knee-oa-cpg-2021'], evidenceStrengthTags: ['moderate'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-knee-oa', title: 'Knee Osteoarthritis', aliases: ['Knee OA'], bodyRegionId: 'region-knee', clinicalSnapshot: 'Load-related knee pain and stiffness with functional limitation in daily tasks.',
      typicalPattern: ['Morning stiffness typically short-duration.', 'Flare-response pattern tied to over/under-loading cycles.'], commonSubjectiveClues: ['Pain with stairs and prolonged walking.', 'Variable swelling and stiffness after heavy days.'],
      objectiveExamPriorities: ['Baseline function (sit-to-stand, gait).', 'Strength deficits and movement confidence.', 'Screen for non-mechanical inflammatory/systemic signs.'],
      keyDifferentialConditionIds: ['condition-meniscal-irritation', 'condition-patellofemoral-pain'], specialTestIds: [],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Settle flare and preserve function.'], treatmentIds: ['tx-education-load-modification'], progressionFocus: ['Pacing and symptom-guided movement'], reassessmentPriorities: ['Flare recovery time', 'daily step tolerance'] },
        { stage: 'chronic', goals: ['Build durable strength and self-management.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Long-term strength + aerobic conditioning'], reassessmentPriorities: ['KOOS-JR/LEFS and participation goals'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-knee-pfp-stepdown'], rationale: 'Transfers to daily functional knee load tolerance.' }],
      healingRecoveryTimeline: ['Chronic condition; aim for symptom control and function gains with ongoing activity rather than cure framing.'], redFlagTopicIds: ['redflag-cancer-systemic', 'redflag-fracture-acute-trauma'],
      commonMistakesPitfalls: ['Rest-only approach during flare.', 'Under-dosing strength and aerobic activity over time.'], evidenceSummary: 'Strong evidence for exercise, education, and long-term self-management.', referenceIds: ['ref-knee-oa-cpg-2021'], evidenceStrengthTags: ['high'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-acl-rehab-overview', title: 'ACL Rehab Overview', aliases: ['ACL injury rehab', 'ACL injury / post-operative rehab', 'ACL injury / post-op'], bodyRegionId: 'region-knee',
      clinicalSnapshot: 'ACL injury pathway requiring staged progression from early impairment management to performance readiness.', typicalPattern: ['Early effusion and strength loss followed by prolonged performance rebuild.', 'Progression should be criteria-based, not calendar-only.'],
      commonSubjectiveClues: ['Instability history during pivot tasks.', 'Confidence gap despite pain improvement.'], objectiveExamPriorities: ['Effusion status and ROM.', 'Strength asymmetry and landing mechanics.', 'Readiness metrics for return-to-sport phases.'],
      keyDifferentialConditionIds: ['condition-meniscal-irritation', 'condition-mcl-sprain'], specialTestIds: ['test-lachman'],
      stageBasedManagement: [
        { stage: 'subacute', goals: ['Restore foundational strength and movement quality.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Quadriceps/hamstring and bilateral-to-unilateral control'], reassessmentPriorities: ['Effusion reactivity', 'strength trend'] },
        { stage: 'return-to-sport', goals: ['Build confidence and high-speed multidirectional capacity.'], treatmentIds: ['tx-progressive-resistance-exercise', 'tx-neuromuscular-balance-retraining'], progressionFocus: ['Plyometric, decel, and change-of-direction progression'], reassessmentPriorities: ['Readiness battery', 'post-session reactivity'] },
      ],
      exerciseProgressionByStage: [{ stage: 'return-to-sport', exerciseProgressionIds: ['ex-acl-strength-plyo'], rationale: 'Provides staged bridge from strength to sport-specific demand.' }],
      healingRecoveryTimeline: ['Recovery duration varies widely by surgery status, goals, and readiness criteria progression.'], redFlagTopicIds: ['redflag-fracture-acute-trauma', 'redflag-progressive-neuro-deficit'],
      commonMistakesPitfalls: ['Time-based RTS without objective criteria.', 'Ignoring psychosocial readiness.'], evidenceSummary: 'Criteria-based progressive rehab is the prevailing model; editorial follow-up needed for latest RTS benchmark evidence synthesis.', referenceIds: ['ref-lachman-evidence'], evidenceStrengthTags: ['moderate'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-lateral-ankle-sprain', title: 'Lateral Ankle Sprain', aliases: ['ATFL/CFL sprain'], bodyRegionId: 'region-ankle-foot',
      clinicalSnapshot: 'Inversion trauma with lateral pain, swelling, and reduced loading tolerance.', typicalPattern: ['Rapid swelling and tenderness lateral ankle.', 'Reinjury risk elevated without full rehab progression.'],
      commonSubjectiveClues: ['Pain with turning/cutting.', 'Prior sprain history common.'], objectiveExamPriorities: ['Fracture screen first (Ottawa).', 'Ligament tenderness and functional control.', 'Single-leg confidence and swelling response.'],
      keyDifferentialConditionIds: ['condition-achilles-tendinopathy', 'condition-plantar-heel-pain'], specialTestIds: ['test-ottawa-ankle'],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Protect and settle swelling/pain.', 'Maintain safe mobility.'], treatmentIds: ['tx-education-load-modification', 'tx-bracing-taping'], progressionFocus: ['Protected weight-bearing and ROM'], reassessmentPriorities: ['Swelling and gait'] },
        { stage: 'subacute', goals: ['Restore calf force and dynamic control.'], treatmentIds: ['tx-progressive-resistance-exercise', 'tx-neuromuscular-balance-retraining'], progressionFocus: ['Calf + balance + hop progression'], reassessmentPriorities: ['Single-leg control', 'LEFS trend'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-ankle-calf-balance'], rationale: 'Builds capacity for return to running and change of direction.' }],
      healingRecoveryTimeline: ['Many grade I-II injuries improve in weeks, but full performance restoration can take longer and should be criteria-based.'], redFlagTopicIds: ['redflag-fracture-acute-trauma'],
      commonMistakesPitfalls: ['Skipping strength/balance phase once pain settles.', 'Premature return to sport.'], evidenceSummary: 'Decision-rule triage plus progressive loading and balance retraining is strongly supported.', referenceIds: ['ref-ankle-cpg-2021', 'ref-ottawa-ankle-rule'], evidenceStrengthTags: ['high'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-achilles-tendinopathy', title: 'Achilles Tendinopathy', aliases: ['Midportion Achilles tendinopathy'], bodyRegionId: 'region-ankle-foot',
      clinicalSnapshot: 'Load-related Achilles pain and stiffness with running/jumping intolerance.', typicalPattern: ['Morning stiffness and first-step pain.', 'Pain increases with energy-storage activities.'],
      commonSubjectiveClues: ['Training volume/intensity change.', 'Local tendon tenderness/thickening.'], objectiveExamPriorities: ['Pain provocation with calf loading.', 'Assess calf strength-endurance deficits.', 'Differentiate insertional vs midportion behavior.'],
      keyDifferentialConditionIds: ['condition-lateral-ankle-sprain', 'condition-plantar-heel-pain'], specialTestIds: [],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Reduce tendon irritability while maintaining activity.'], treatmentIds: ['tx-education-load-modification'], progressionFocus: ['Isometric/concentric entry loading'], reassessmentPriorities: ['Morning pain trend', '24-hour load response'] },
        { stage: 'subacute', goals: ['Build tendon and calf capacity.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Progressive heavy-slow or energy-storage progression'], reassessmentPriorities: ['Single-leg calf endurance', 'running tolerance'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-ankle-calf-balance'], rationale: 'Provides practical pathway toward higher-load tendon demands.' }],
      healingRecoveryTimeline: ['Often a longer rehab arc; staged tendon loading over months is common in active populations.'], redFlagTopicIds: ['redflag-fracture-acute-trauma'],
      commonMistakesPitfalls: ['Stopping all loading for prolonged periods.', 'Progressing plyometrics before calf capacity is restored.'], evidenceSummary: 'Progressive loading is central; editorial follow-up needed for insertional-specific dose guidance references.', referenceIds: ['ref-acsm-loading'], evidenceStrengthTags: ['moderate'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-plantar-heel-pain', title: 'Plantar Heel Pain', aliases: ['Plantar fasciopathy'], bodyRegionId: 'region-ankle-foot',
      clinicalSnapshot: 'Inferomedial heel pain, often worst on first steps and after prolonged loading.', typicalPattern: ['Morning first-step pain hallmark.', 'Symptoms rise with prolonged standing/walking.'],
      commonSubjectiveClues: ['Gradual onset with step count/workload changes.', 'Pain localized near medial calcaneal tubercle.'], objectiveExamPriorities: ['Palpation and windlass loading response.', 'Calf-ankle mobility and plantarflexor strength profile.'],
      keyDifferentialConditionIds: ['condition-achilles-tendinopathy'], specialTestIds: [],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Reduce first-step pain and activity intolerance.'], treatmentIds: ['tx-education-load-modification', 'tx-bracing-taping'], progressionFocus: ['Footwear/load adjustments and early strength'], reassessmentPriorities: ['Morning pain severity', 'standing tolerance'] },
        { stage: 'subacute', goals: ['Restore foot-ankle load tolerance for walking/running.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Calf/foot intrinsic progression'], reassessmentPriorities: ['LEFS/PSFS', 'daily step tolerance'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-ankle-calf-balance'], rationale: 'Targets plantarflexor and foot load capacity deficits.' }],
      healingRecoveryTimeline: ['Commonly improves with consistent loading and footwear/activity management over weeks to months.'], redFlagTopicIds: ['redflag-fracture-acute-trauma'],
      commonMistakesPitfalls: ['Over-reliance on passive modalities only.', 'Ignoring load spikes and footwear contributors.'], evidenceSummary: 'Exercise-led management with load and footwear strategy is common best practice; evidence depth varies by intervention type.', referenceIds: ['ref-acsm-loading'], evidenceStrengthTags: ['moderate'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-nonspecific-low-back-pain', title: 'Non-Specific Low Back Pain', aliases: ['NSLBP'], bodyRegionId: 'region-lumbar-spine',
      clinicalSnapshot: 'Low back pain without clear serious pathology or specific structural diagnosis requiring different pathway.', typicalPattern: ['Variable pain with movement/posture/loading.', 'Functional limitation often disproportionate to tissue-label certainty.'],
      commonSubjectiveClues: ['Recent load/stress/sleep disruption.', 'Fear-avoidance behaviors limiting activity.'], objectiveExamPriorities: ['Red flag and neuro screen.', 'Movement tolerance profile and preferred directional strategies.', 'Function-focused baseline measures.'],
      keyDifferentialConditionIds: ['condition-lumbar-radicular-pain'], specialTestIds: [],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Reduce threat and maintain activity.'], treatmentIds: ['tx-education-load-modification', 'tx-manual-therapy-adjunct'], progressionFocus: ['Frequent low-dose movement'], reassessmentPriorities: ['Confidence trend', 'daily activity tolerance'] },
        { stage: 'subacute', goals: ['Rebuild trunk/hip capacity and function.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Graded lifting/bending/carrying'], reassessmentPriorities: ['ODI/PSFS', 'work/ADL tolerance'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-lumbar-graded-activity'], rationale: 'Builds capacity while preserving activity participation.' }],
      healingRecoveryTimeline: ['Most acute episodes improve within weeks, but recurrence is common; long-term self-management is key.'], redFlagTopicIds: ['redflag-cauda-equina', 'redflag-cancer-systemic', 'redflag-progressive-neuro-deficit'],
      commonMistakesPitfalls: ['Imaging-first approach without red flags.', 'Bed rest and movement avoidance.'], evidenceSummary: 'Guidelines strongly support education, activity continuation, and exercise-based care.', referenceIds: ['ref-lbp-cpg-2021'], evidenceStrengthTags: ['high'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-lumbar-radicular-pain', title: 'Lumbar Radicular Pain', aliases: ['Sciatica pattern'], bodyRegionId: 'region-lumbar-spine',
      clinicalSnapshot: 'Back-related leg pain with neurodynamic or neurological features suggesting nerve root involvement.', typicalPattern: ['Leg-dominant symptoms below knee in many cases.', 'Symptoms may worsen with prolonged sitting, flexion, cough/sneeze.'],
      commonSubjectiveClues: ['Dermatomal pain/paresthesia profile.', 'Intermittent weakness or heaviness in limb.'], objectiveExamPriorities: ['Neuro exam (myotomes/reflex/sensation).', 'Neurodynamic tests with structural differentiation.', 'Red-flag neurological progression screen.'],
      keyDifferentialConditionIds: ['condition-nonspecific-low-back-pain'], specialTestIds: ['test-slump'],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Settle severe neural irritability and maintain function.'], treatmentIds: ['tx-education-load-modification', 'tx-nerve-mobility'], progressionFocus: ['Neural slider entry dosing'], reassessmentPriorities: ['Neuro deficit trajectory', 'pain distribution changes'] },
        { stage: 'subacute', goals: ['Restore loading tolerance and confidence.'], treatmentIds: ['tx-progressive-resistance-exercise', 'tx-nerve-mobility'], progressionFocus: ['Trunk-hip loading with graded neural exposure'], reassessmentPriorities: ['ODI/PSFS', 'walking/sitting tolerance'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-lumbar-graded-activity'], rationale: 'Integrates neural symptom management with capacity restoration.' }],
      healingRecoveryTimeline: ['Many improve over weeks to months; monitor closely for progressive neurological signs requiring escalation.'], redFlagTopicIds: ['redflag-cauda-equina', 'redflag-progressive-neuro-deficit', 'redflag-cancer-systemic'],
      commonMistakesPitfalls: ['Ignoring objective neuro change over time.', 'Overly aggressive neural tensioning early.'], evidenceSummary: 'Multimodal conservative care is common first-line when no emergency signs are present.', referenceIds: ['ref-lbp-cpg-2021'], evidenceStrengthTags: ['moderate'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-neck-mobility-deficits', title: 'Neck Pain with Mobility Deficits', aliases: ['Mechanical neck pain'], bodyRegionId: 'region-cervical-spine',
      clinicalSnapshot: 'Neck pain with movement restriction and activity-provoked symptoms without major neurological compromise.', typicalPattern: ['Pain and stiffness with rotation/extension.', 'Postural endurance intolerance common.'],
      commonSubjectiveClues: ['Pain with desk/driving tasks.', 'Episodic flares linked to workload/stress.'], objectiveExamPriorities: ['Cervical and thoracic mobility deficits.', 'Scapular and deep neck flexor endurance.', 'Screen for radicular and vascular red flags.'],
      keyDifferentialConditionIds: ['condition-cervicogenic-headache', 'condition-carpal-tunnel-syndrome'], specialTestIds: ['test-upper-limb-tension-1'],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Reduce pain and restore tolerable movement.'], treatmentIds: ['tx-education-load-modification', 'tx-manual-therapy-adjunct'], progressionFocus: ['Frequent ROM and symptom-limited activity'], reassessmentPriorities: ['NDI and ROM trend'] },
        { stage: 'subacute', goals: ['Build endurance and sustained posture capacity.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Deep neck flexor + scapular endurance'], reassessmentPriorities: ['Work tolerance', 'headache/neck frequency'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-neck-mobility-endurance'], rationale: 'Systematically progresses mobility and endurance to function.' }],
      healingRecoveryTimeline: ['Many episodes improve over weeks; recurrence risk reduced with ongoing exercise and self-management.'], redFlagTopicIds: ['redflag-progressive-neuro-deficit', 'redflag-cancer-systemic'],
      commonMistakesPitfalls: ['Passive-only care with no active progression.', 'Missing thoracic contribution.'], evidenceSummary: 'Exercise plus adjunct manual therapy has strong guideline support for many neck mobility-deficit presentations.', referenceIds: ['ref-neck-cpg-2017'], evidenceStrengthTags: ['high'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-cervicogenic-headache', title: 'Cervicogenic Headache', aliases: ['CGH'], bodyRegionId: 'region-cervical-spine',
      clinicalSnapshot: 'Headache linked to cervical dysfunction, often unilateral and associated with neck pain/stiffness.', typicalPattern: ['Headache provoked by neck posture/movement.', 'Upper cervical tenderness and movement restriction common.'],
      commonSubjectiveClues: ['Neck pain preceding headache.', 'Reduced headache with cervical symptom improvements.'], objectiveExamPriorities: ['Upper cervical mobility and symptom reproduction.', 'Deep neck flexor endurance and scapular support.', 'Exclude other headache red flags.'],
      keyDifferentialConditionIds: ['condition-neck-mobility-deficits'], specialTestIds: [],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Reduce headache frequency/intensity and neck irritability.'], treatmentIds: ['tx-education-load-modification', 'tx-manual-therapy-adjunct'], progressionFocus: ['Gentle mobility and headache trigger management'], reassessmentPriorities: ['Headache diary trend', 'NDI/PSFS'] },
        { stage: 'subacute', goals: ['Improve cervical endurance and recurrence prevention.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Endurance and postural loading progression'], reassessmentPriorities: ['Headache-free days', 'activity tolerance'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-neck-mobility-endurance'], rationale: 'Addresses mobility deficits and endurance contributors to headache recurrence.' }],
      healingRecoveryTimeline: ['Symptoms often improve over weeks with consistent cervical rehab and trigger management; recurrence patterns vary.'], redFlagTopicIds: ['redflag-cancer-systemic', 'redflag-progressive-neuro-deficit'],
      commonMistakesPitfalls: ['Treating headache without cervical functional progression.', 'Insufficient differential screen for non-cervicogenic headache causes.'], evidenceSummary: 'Exercise and manual therapy combination commonly recommended; editorial follow-up for headache-specific high-level reviews.', referenceIds: ['ref-neck-cpg-2017'], evidenceStrengthTags: ['moderate'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-lateral-epicondylalgia', title: 'Lateral Epicondylalgia', aliases: ['Lateral elbow tendinopathy'], bodyRegionId: 'region-elbow-forearm',
      clinicalSnapshot: 'Lateral elbow pain aggravated by gripping, wrist extension, and forearm loading.', typicalPattern: ['Load-related pain over common extensor origin.', 'Symptoms can become persistent with repetitive load exposure.'],
      commonSubjectiveClues: ['Pain with gripping/lifting cup/pan.', 'Work or sport overuse history.'], objectiveExamPriorities: ['Resisted wrist/finger extension pain response.', 'Grip strength asymmetry.', 'Screen cervical/radial tunnel contributions.'],
      keyDifferentialConditionIds: ['condition-carpal-tunnel-syndrome'], specialTestIds: ['test-cozen', 'test-maudsley'],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Reduce tendon irritability and preserve use.'], treatmentIds: ['tx-education-load-modification', 'tx-bracing-taping'], progressionFocus: ['Isometric and load modification entry'], reassessmentPriorities: ['Grip tolerance trend'] },
        { stage: 'subacute', goals: ['Rebuild extensor tendon load capacity.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Wrist extensor progressive loading'], reassessmentPriorities: ['QuickDASH/PSFS', 'task tolerance'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-neck-mobility-endurance'], rationale: 'Editorial follow-up: replace with dedicated elbow progression module.' }],
      healingRecoveryTimeline: ['May require sustained loading progression over months; avoid false precision on duration.'], redFlagTopicIds: ['redflag-progressive-neuro-deficit'],
      commonMistakesPitfalls: ['Passive modalities only.', 'Ignoring grip/load dosing in work tasks.'], evidenceSummary: 'Progressive loading and activity modification are mainstays; higher-quality elbow-specific protocol synthesis is an editorial priority.', referenceIds: ['ref-acsm-loading'], evidenceStrengthTags: ['moderate', 'expert-consensus'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-de-quervains', title: 'de Quervain’s Tenosynovitis', aliases: ['de Quervain syndrome'], bodyRegionId: 'region-hand-wrist',
      clinicalSnapshot: 'Radial wrist pain with thumb motion and gripping/lifting.', typicalPattern: ['Pain around radial styloid with repetitive thumb use.', 'Mother’s thumb/caregiving loads are common aggravators.'],
      commonSubjectiveClues: ['Pain with lifting infant, gripping, texting.', 'Local tenderness over first dorsal compartment.'], objectiveExamPriorities: ['Local palpation and movement provocation.', 'Rule out thumb CMC OA and radial nerve irritability.'],
      keyDifferentialConditionIds: ['condition-carpal-tunnel-syndrome'], specialTestIds: ['test-finkelstein'],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Settle local tendon sheath irritation.'], treatmentIds: ['tx-education-load-modification', 'tx-bracing-taping'], progressionFocus: ['Thumb/wrist load modification and splint strategy'], reassessmentPriorities: ['Pain with caregiving/work tasks'] },
        { stage: 'subacute', goals: ['Restore thumb/wrist loading tolerance.'], treatmentIds: ['tx-progressive-resistance-exercise'], progressionFocus: ['Gradual thumb abduction/extension and grip progression'], reassessmentPriorities: ['QuickDASH/PSFS', 'task exposure tolerance'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-shoulder-cuff-loading'], rationale: 'Editorial follow-up: replace with dedicated hand/wrist progression.' }],
      healingRecoveryTimeline: ['Often improves over weeks with load modification and staged reloading; some require medical escalation pathways.'], redFlagTopicIds: ['redflag-fracture-acute-trauma'],
      commonMistakesPitfalls: ['No load modification for caregiving/work triggers.', 'Overly provocative testing/exercise dosing early.'], evidenceSummary: 'Conservative care is frequently effective, but evidence quality and optimal sequencing remain variable.', referenceIds: ['ref-dequervain'], evidenceStrengthTags: ['low', 'expert-consensus'], lastReviewed: REVIEW_METADATA,
    },
    {
      id: 'condition-carpal-tunnel-syndrome', title: 'Carpal Tunnel Syndrome', aliases: ['CTS'], bodyRegionId: 'region-hand-wrist',
      clinicalSnapshot: 'Median nerve compression pattern with nocturnal paresthesia and hand functional symptoms.', typicalPattern: ['Numbness/tingling in thumb-index-middle fingers.', 'Night symptoms and repetitive hand-use aggravation common.'],
      commonSubjectiveClues: ['Shaking hand for relief at night.', 'Grip fatigue or fine motor difficulty.'], objectiveExamPriorities: ['Sensory map and thenar function screen.', 'Phalen/Tinel as adjuncts.', 'Cervical/proximal neural differential as needed.'],
      keyDifferentialConditionIds: ['condition-neck-mobility-deficits', 'condition-lateral-epicondylalgia'], specialTestIds: ['test-phalen', 'test-tinel-carpal-tunnel', 'test-upper-limb-tension-1'],
      stageBasedManagement: [
        { stage: 'acute-irritable', goals: ['Reduce nocturnal and repetitive-use symptom burden.'], treatmentIds: ['tx-education-load-modification', 'tx-bracing-taping'], progressionFocus: ['Night splinting and ergonomic load changes'], reassessmentPriorities: ['Night symptom frequency', 'hand numbness severity'] },
        { stage: 'subacute', goals: ['Improve nerve and hand function tolerance.'], treatmentIds: ['tx-nerve-mobility', 'tx-progressive-resistance-exercise'], progressionFocus: ['Nerve slider progression and hand/forearm conditioning'], reassessmentPriorities: ['QuickDASH/PSFS', 'work-task tolerance'] },
      ],
      exerciseProgressionByStage: [{ stage: 'subacute', exerciseProgressionIds: ['ex-neck-mobility-endurance'], rationale: 'Editorial follow-up: replace with dedicated median nerve + hand capacity progression module.' }],
      healingRecoveryTimeline: ['Variable trajectory; monitor for progression of sensory/motor deficits requiring medical escalation.'], redFlagTopicIds: ['redflag-progressive-neuro-deficit'],
      commonMistakesPitfalls: ['Delayed referral despite progressive motor deficit.', 'Ignoring proximal neural/cervical contributors.'], evidenceSummary: 'Conservative care can help mild-moderate cases; escalation needed for progressive neurological compromise.', referenceIds: ['ref-carpal-tunnel'], evidenceStrengthTags: ['moderate'], lastReviewed: REVIEW_METADATA,
    },
  ],
};

export const clinicalSeedIndexes = buildClinicalIndexes(clinicalSeed);
export const clinicalReferenceMap = buildReferenceMap(clinicalSeed.references);

export function getConditionViewSamples(view: 'quick'): ConditionQuickView[];
export function getConditionViewSamples(view: 'deep'): ConditionDeepView[];
export function getConditionViewSamples(view: ViewDensity): Array<ConditionQuickView | ConditionDeepView> {
  return clinicalSeed.conditions.map((condition) => toConditionView(condition, view));
}
