import {
  buildClinicalIndexes,
  buildReferenceMap,
  type ClinicalContentStore,
  type ConditionDeepView,
  type ConditionQuickView,
  type ViewDensity,
  toConditionView,
} from '@/lib/clinicalContentModel';

export const clinicalSeed: ClinicalContentStore = {
  bodyRegions: [
    {
      id: 'region-shoulder',
      key: 'shoulder',
      name: 'Shoulder',
      aliases: ['Glenohumeral region', 'Subacromial region'],
      tags: ['upper-quarter', 'overhead-athlete'],
    },
    {
      id: 'region-knee',
      key: 'knee',
      name: 'Knee',
      aliases: ['Tibiofemoral region', 'Patellofemoral region'],
      tags: ['lower-quarter', 'running'],
    },
    {
      id: 'region-ankle-foot',
      key: 'ankle-foot',
      name: 'Ankle & Foot',
      aliases: ['Talocrural region', 'Hindfoot'],
      tags: ['lower-quarter', 'sport'],
    },
  ],
  references: [
    {
      id: 'ref-rcsp-cpg-2022',
      shortLabel: 'JOSPT CPG 2022',
      type: 'guideline',
      title: 'Rotator Cuff Tendinopathy Diagnosis, Non-surgical Medical Care, and Rehabilitation: A Clinical Practice Guideline',
      authors: ['Ludewig PM', 'Reiman MP', 'et al.'],
      year: 2022,
      journalOrSource: 'Journal of Orthopaedic & Sports Physical Therapy',
      doi: '10.2519/jospt.2022.0302',
      url: 'https://www.jospt.org/doi/10.2519/jospt.2022.0302',
    },
    {
      id: 'ref-hawkins-meta',
      shortLabel: 'Hegedus 2012',
      type: 'systematic-review',
      title: 'Physical examination tests of the shoulder: a systematic review with meta-analysis of individual tests',
      authors: ['Hegedus EJ', 'Goode A', 'Campbell S', 'et al.'],
      year: 2012,
      journalOrSource: 'British Journal of Sports Medicine',
      doi: '10.1136/bjsports-2012-091066',
      url: 'https://bjsm.bmj.com/content/46/14/964',
    },
    {
      id: 'ref-quickdash',
      shortLabel: 'QuickDASH validation',
      type: 'cohort',
      title: 'The QuickDASH outcome measure: reliability and validity in upper-extremity disorders',
      authors: ['Beaton DE', 'Wright JG', 'Katz JN'],
      year: 2005,
      journalOrSource: 'Journal of Bone and Joint Surgery',
    },
    {
      id: 'ref-red-flag-cancer',
      shortLabel: 'NICE NG12',
      type: 'guideline',
      title: 'Suspected cancer: recognition and referral',
      authors: ['National Institute for Health and Care Excellence'],
      year: 2023,
      journalOrSource: 'NICE guideline NG12',
      url: 'https://www.nice.org.uk/guidance/ng12',
    },
    {
      id: 'ref-ottawa-ankle-rule',
      shortLabel: 'Ottawa Ankle Rules',
      type: 'diagnostic-study',
      title: 'Implementation of the Ottawa ankle rules',
      authors: ['Stiell IG', 'et al.'],
      year: 1994,
      journalOrSource: 'JAMA',
      doi: '10.1001/jama.271.11.827',
      url: 'https://jamanetwork.com/journals/jama/article-abstract/370516',
    },
    {
      id: 'ref-lachman-evidence',
      shortLabel: 'ACL test meta-analysis',
      type: 'systematic-review',
      title: 'Clinical diagnosis of anterior cruciate ligament rupture: a meta-analysis',
      authors: ['Benjaminse A', 'et al.'],
      year: 2006,
      journalOrSource: 'J Orthop Sports Phys Ther',
    },
  ],
  specialTests: [
    {
      id: 'test-hawkins-kennedy',
      title: 'Hawkins-Kennedy Test',
      aliases: ['Hawkins test'],
      assesses: 'Subacromial pain provocation / rotator cuff related shoulder pain cluster',
      bodyRegionId: 'region-shoulder',
      targetStructureOrDiagnosis: 'Rotator cuff related shoulder pain',
      testPurpose: 'Symptom provocation as part of a shoulder pain diagnostic cluster, not a stand-alone diagnosis.',
      patientPosition: 'Sitting or standing; shoulder and elbow flexed to approximately 90 degrees.',
      clinicianAction: [
        'Stabilize scapula and proximal humerus.',
        'Passively internally rotate the humerus in horizontal adduction.',
      ],
      positiveFinding: 'Reproduction of familiar anterolateral shoulder pain.',
      interpretation: 'Supports subacromial pain hypothesis when combined with history and other exam findings.',
      limitations: [
        'Can be positive in multiple shoulder pain diagnoses.',
        'Irritable shoulders may react to non-specific compression pain.',
      ],
      diagnosticUtilityNotes: [
        'Use as part of a test cluster and load response findings.',
        'Avoid over-reliance on sensitivity/specificity from single studies.',
      ],
      evidenceNotes: 'Moderate-quality evidence suggests limited stand-alone utility; better when integrated with cluster reasoning.',
      relatedConditionIds: ['condition-rcrsp'],
      referenceIds: ['ref-hawkins-meta', 'ref-rcsp-cpg-2022'],
    },
    {
      id: 'test-empty-can',
      title: 'Empty Can (Jobe) Test',
      aliases: ['Jobe test'],
      assesses: 'Supraspinatus load tolerance / rotator cuff pain provocation',
      bodyRegionId: 'region-shoulder',
      targetStructureOrDiagnosis: 'Rotator cuff related shoulder pain',
      testPurpose: 'Adds to rotator cuff hypothesis when weakness or pain with elevation is part of the clinical story.',
      patientPosition: 'Sitting or standing; shoulder in ~90° scaption, thumb down.',
      clinicianAction: [
        'Ask patient to hold position in scaption.',
        'Apply downward resistance at distal forearm while patient resists.',
      ],
      positiveFinding: 'Reproduction of familiar pain and/or notable side-to-side weakness.',
      interpretation: 'Improves confidence in rotator cuff involvement when paired with history, painful arc, and load-response testing.',
      limitations: [
        'Pain-limited effort can mimic true weakness.',
        'Not specific enough to isolate supraspinatus structural pathology.',
      ],
      diagnosticUtilityNotes: [
        'Interpret alongside active range, resisted external rotation, and symptom behavior over 24 hours.',
        'Use to guide loading entry point rather than to label tissue damage.',
      ],
      evidenceNotes: 'Useful in a cluster approach; stand-alone positive finding has limited certainty.',
      relatedConditionIds: ['condition-rcrsp'],
      referenceIds: ['ref-hawkins-meta', 'ref-rcsp-cpg-2022'],
    },
    {
      id: 'test-lachman',
      title: 'Lachman Test',
      aliases: ['Anterior stability test'],
      assesses: 'Anterior cruciate ligament integrity',
      bodyRegionId: 'region-knee',
      targetStructureOrDiagnosis: 'ACL tear',
      testPurpose: 'Screens for ACL insufficiency after twisting injury with instability/giving-way history.',
      patientPosition: 'Supine with knee flexed around 20-30°.',
      clinicianAction: [
        'Stabilize distal femur with one hand.',
        'Translate proximal tibia anteriorly with the other hand, assessing end-feel and excursion.',
      ],
      positiveFinding: 'Increased anterior tibial translation and softer end-feel versus contralateral knee.',
      interpretation: 'Raises suspicion for ACL disruption, especially with acute effusion and pivoting mechanism.',
      limitations: [
        'Acute guarding/pain can reduce test quality.',
        'Comparison can be misleading in hyperlax individuals.',
      ],
      diagnosticUtilityNotes: [
        'Pair with mechanism of injury, swelling timeline, and functional instability report.',
        'Consider cluster with anterior drawer and pivot shift where tolerated.',
      ],
      evidenceNotes: 'Often among the highest-yield ACL exam tests but still requires clinical context and imaging when indicated.',
      relatedConditionIds: ['condition-acl-sprain'],
      referenceIds: ['ref-lachman-evidence'],
    },
    {
      id: 'test-ottawa-ankle',
      title: 'Ottawa Ankle Rules',
      aliases: ['OAR'],
      assesses: 'Need for ankle/foot radiography after acute injury',
      bodyRegionId: 'region-ankle-foot',
      targetStructureOrDiagnosis: 'Acute ankle/foot fracture screening',
      testPurpose: 'Helps answer whether immediate imaging is indicated after ankle/foot trauma.',
      patientPosition: 'Standing or supine, depending on pain tolerance.',
      clinicianAction: [
        'Palpate posterior edge/tips of both malleoli, base of 5th metatarsal, and navicular.',
        'Assess whether patient can bear weight for four steps immediately and in clinic.',
      ],
      positiveFinding: 'Bone tenderness at Ottawa rule sites and/or inability to bear weight for four steps.',
      interpretation: 'Positive rule supports need for radiography; negative rule lowers fracture probability in appropriate populations.',
      limitations: [
        'Validated mainly for acute trauma populations, not delayed/chronic pain.',
        'Not a ligament severity test; only supports imaging decision-making.',
      ],
      diagnosticUtilityNotes: [
        'Combine with neurovascular exam and mechanism to prioritize urgent referral versus conservative care.',
        'Reassess if symptoms worsen despite initially negative rule.',
      ],
      evidenceNotes: 'High sensitivity in acute settings supports use as a triage rule, not a definitive diagnosis.',
      relatedConditionIds: ['condition-lateral-ankle-sprain'],
      referenceIds: ['ref-ottawa-ankle-rule'],
    },
  ],
  treatments: [
    {
      id: 'tx-education-load-modification',
      title: 'Education + Load Modification',
      aliases: ['Activity modification coaching'],
      whatItIs: 'Collaborative planning of symptom-guided loading, sleep/posture factors, and realistic recovery expectations.',
      whenToUse: ['Early management of irritable shoulder pain.', 'When pain behaviors or fear are limiting movement exposure.'],
      whenNotToOveruse: ['Do not prolong unloading past symptom settling window.', 'Avoid framing pain as tissue damage certainty.'],
      stageRelevance: ['acute-irritable', 'subacute', 'chronic'],
      indications: ['Night pain with high irritability.', 'Pain spike after rapid load increase.'],
      contraindicationsPrecautions: ['Screen for non-musculoskeletal red flags before conservative care-only approach.'],
      practicalNotes: [
        'Set a pain-monitoring rule (during exercise <=5/10 and returns to baseline in 24 hours).',
        'Translate loading advice into patient-specific tasks (sleep, work, gym, childcare).',
      ],
      evidenceSummary: 'Strong guideline-level support as a first-line component, especially when combined with progressive exercise.',
      referenceIds: ['ref-rcsp-cpg-2022'],
    },
    {
      id: 'tx-progressive-resistance-exercise',
      title: 'Progressive Resistance Exercise',
      aliases: ['Progressive loading program'],
      whatItIs: 'Structured strengthening progression based on symptom response, movement quality, and function goals.',
      whenToUse: ['Subacute to chronic rehab when irritability is controllable.', 'When force deficits or deconditioning limit function.'],
      whenNotToOveruse: ['Avoid abrupt load jumps after symptom flare.', 'Do not progress only by pain suppression without quality control.'],
      stageRelevance: ['subacute', 'chronic', 'post-op-late', 'return-to-sport'],
      indications: ['Task-specific weakness.', 'Low confidence with loaded movement.'],
      contraindicationsPrecautions: ['Respect post-op tissue protection timelines and surgeon restrictions where relevant.'],
      practicalNotes: [
        'Use objective anchors (reps in reserve, load used, symptom response next day).',
        'Progress one variable at a time: load, range, speed, or complexity.',
      ],
      evidenceSummary: 'Strong evidence across MSK conditions that progressive exercise improves pain and function versus passive care-only approaches.',
      referenceIds: ['ref-rcsp-cpg-2022'],
    },
    {
      id: 'tx-neuromuscular-balance-retraining',
      title: 'Neuromuscular + Balance Retraining',
      aliases: ['Sensorimotor retraining'],
      whatItIs: 'Task-oriented stability, balance, and control exercises to improve movement strategy and reduce recurrence risk.',
      whenToUse: ['After acute ankle sprain once weight-bearing is tolerated.', 'During late-stage return-to-sport planning.'],
      whenNotToOveruse: ['Avoid highly unstable drills before basic strength and pain control are present.'],
      stageRelevance: ['subacute', 'chronic', 'return-to-sport'],
      indications: ['Recurrent instability episodes.', 'Poor single-leg control or confidence.'],
      contraindicationsPrecautions: ['Guard against unsafe challenge level in high fall-risk patients.'],
      practicalNotes: [
        'Progress from stable to variable surfaces and from predictable to reactive tasks.',
        'Pair with calf/peroneal strengthening for better transfer to field and court tasks.',
      ],
      evidenceSummary: 'Moderate-to-strong evidence supports neuromuscular retraining to reduce recurrent ankle sprain risk.',
      referenceIds: ['ref-ottawa-ankle-rule'],
    },
  ],
  exerciseProgressions: [
    {
      id: 'ex-shoulder-isometric-to-isotonic-abduction',
      title: 'Rotator Cuff Loading Progression: Isometric to Isotonic Abduction',
      aliases: ['Shoulder abduction loading ladder'],
      targetConditionIds: ['condition-rcrsp'],
      targetTissuesFunctions: ['Supraspinatus/infraspinatus load tolerance', 'Scapulohumeral control'],
      stage: 'subacute',
      entryCriteria: ['Resting pain stable for 48-72 hours.', 'Able to elevate arm to 90 degrees with acceptable pain response.'],
      dosageSuggestions: ['Isometric: 5 x 30-45 second holds @ 4-6/10 effort.', 'Isotonic: 3 x 8-12 reps, 2-3 sessions/week.'],
      commonCompensations: ['Upper trapezius dominance / shoulder hiking', 'Lumbar extension to substitute elevation'],
      progressionOptions: ['Increase lever arm or external load.', 'Advance to 90-120 degree scaption arc.'],
      regressionOptions: ['Reduce arc to pain-tolerable range.', 'Return to shorter isometric holds with lower effort.'],
      criteriaToAdvance: [
        'No night pain increase and no >24-hour flare after sessions.',
        'Can complete target reps with controlled scapulohumeral rhythm.',
      ],
      returnToFunctionRelevance: 'Builds overhead tolerance for work, ADLs, and graded return to sport.',
      evidenceNotes: 'Progressive resistance shows superior medium-term outcomes versus passive care alone for rotator cuff related shoulder pain.',
      referenceIds: ['ref-rcsp-cpg-2022'],
    },
    {
      id: 'ex-ankle-calf-raise-progression',
      title: 'Ankle Plantarflexor Progression: Bilateral to Single-Leg Calf Raise',
      aliases: ['Calf raise ladder'],
      targetConditionIds: ['condition-lateral-ankle-sprain'],
      targetTissuesFunctions: ['Gastrocnemius/soleus force capacity', 'Ankle stiffness and push-off control'],
      stage: 'subacute',
      entryCriteria: ['Able to walk with acceptable pain response.', 'Can perform double-leg heel raise with control.'],
      dosageSuggestions: ['3-4 sets of 8-15 reps, 2-4 times/week.', 'Add tempo or external load once bodyweight is controlled.'],
      commonCompensations: ['Weight shift to uninvolved side', 'Rapid heel drop without eccentric control'],
      progressionOptions: ['Move to single-leg raises.', 'Progress to loaded raises and faster concentric intent.'],
      regressionOptions: ['Reduce range at end-range discomfort.', 'Use hand support and bilateral loading.'],
      criteriaToAdvance: ['>=25 controlled single-leg raises or symmetry with contralateral limb.', 'No increase in swelling next day.'],
      returnToFunctionRelevance: 'Restores propulsion capacity for gait, stairs, running, and change-of-direction readiness.',
      evidenceNotes: 'Progressive calf loading is a core component in restoring ankle function after sprain-related deconditioning.',
      referenceIds: ['ref-ottawa-ankle-rule'],
    },
    {
      id: 'ex-knee-quad-strength-control',
      title: 'Knee Quadriceps Progression: Sit-to-Stand to Split Squat',
      aliases: ['Knee extensor loading continuum'],
      targetConditionIds: ['condition-acl-sprain'],
      targetTissuesFunctions: ['Quadriceps force production', 'Frontal-plane knee control'],
      stage: 'post-op-late',
      entryCriteria: ['Pain and swelling stable.', 'Can perform controlled sit-to-stand without dynamic valgus collapse.'],
      dosageSuggestions: ['3-5 sets of 5-10 reps for strength-focused work, 2-3 sessions/week.', 'Add accessory endurance set (12-15 reps) as tolerated.'],
      commonCompensations: ['Hip shift off affected side', 'Trunk collapse and knee valgus on descent'],
      progressionOptions: ['Advance to split squat and rear-foot elevated split squat.', 'Introduce deceleration-focused tempo and loaded carries.'],
      regressionOptions: ['Reduce depth or external load.', 'Return to box-supported sit-to-stand patterns.'],
      criteriaToAdvance: ['Demonstrates symmetrical control and acceptable pain response across 2 consecutive sessions.', 'Meets agreed strength benchmark for stage goals.'],
      returnToFunctionRelevance: 'Builds unilateral force and control required before landing, cutting, and return-to-sport progressions.',
      evidenceNotes: 'Quadriceps strength restoration is strongly associated with improved function and return-to-sport readiness after ACL injury pathways.',
      referenceIds: ['ref-lachman-evidence'],
    },
  ],
  outcomeMeasures: [
    {
      id: 'om-quickdash',
      title: 'QuickDASH',
      aliases: ['Quick Disabilities of the Arm, Shoulder and Hand'],
      bodyRegionId: 'region-shoulder',
      population: 'Adults with upper-extremity musculoskeletal disorders.',
      conditionRelevanceConditionIds: ['condition-rcrsp'],
      administration: ['11-item self-report questionnaire.', 'Score each item 1-5 and transform to 0-100 scale.'],
      scoring: ['Higher score = greater disability.', 'Track change over 2-6 week intervals in active rehab.'],
      mcidMdc: ['MCID often reported around 8-15 points depending on population.', 'Use local population benchmarks when available.'],
      interpretation: ['Combine with pain intensity and function-specific goals.', 'Large score shifts without functional changes should prompt context review.'],
      referenceIds: ['ref-quickdash'],
    },
  ],
  redFlags: [
    {
      id: 'redflag-nonmechanical-night-pain-weight-loss',
      title: 'Potential Serious Pathology in Shoulder Pain Presentation',
      aliases: ['Cancer red flag cluster'],
      scenario: 'Shoulder pain that is progressive, non-mechanical, severe at night, with unexplained weight loss or systemic malaise.',
      whyItMatters: 'Can indicate metastatic or primary pathology requiring urgent medical workup.',
      whatToAsk: ['Unintentional weight loss?', 'History of cancer?', 'Fever, night sweats, persistent fatigue?'],
      whatToLookFor: ['Pain not modified by movement/load.', 'Visible wasting or unexplained neurological deficits.'],
      escalationPathway: ['Stop routine load progression.', 'Communicate concern and same-day medical referral.', 'Document safety-net advice and follow-up contact.'],
      referralUrgency: 'urgent-24h',
      referenceIds: ['ref-red-flag-cancer'],
    },
  ],
  conditions: [
    {
      id: 'condition-rcrsp',
      title: 'Rotator Cuff Related Shoulder Pain',
      aliases: ['RCRSP', 'Subacromial shoulder pain syndrome'],
      bodyRegionId: 'region-shoulder',
      clinicalSnapshot: 'Load-sensitive shoulder pain with painful arc and reduced tolerance for overhead tasks, usually without full-thickness traumatic tear signs.',
      typicalPattern: [
        'Pain aggravated by overhead loading, reaching, and side-lying on involved shoulder.',
        'Variable night pain and morning stiffness lasting under 30 minutes in non-inflammatory presentations.',
      ],
      commonSubjectiveClues: [
        'Pain after abrupt training/volume increase.',
        'Difficulty with hand-behind-back tasks and overhead dressing.',
        'Temporary easing with relative rest but flare on reload.',
      ],
      objectiveExamPriorities: [
        'Asterisk signs: painful arc, resisted abduction/external rotation symptom response.',
        'Rule in/out cervical contribution and glenohumeral stiffness pattern.',
        'Assess irritability to set initial loading threshold.',
      ],
      keyDifferentialConditionIds: ['condition-adhesive-capsulitis'],
      specialTestIds: ['test-hawkins-kennedy'],
      stageBasedManagement: [
        {
          stage: 'acute-irritable',
          goals: ['Reduce symptom volatility.', 'Maintain tolerated shoulder movement.'],
          treatmentIds: ['tx-education-load-modification'],
          progressionFocus: ['Short-lever isometrics', 'Sleep and daily load adjustments'],
          reassessmentPriorities: ['Night pain trend', '24-hour response to loading'],
        },
        {
          stage: 'subacute',
          goals: ['Restore force production and confidence with overhead function.'],
          treatmentIds: ['tx-education-load-modification', 'tx-progressive-resistance-exercise'],
          progressionFocus: ['Progressive resistance through tolerated arcs'],
          reassessmentPriorities: ['QuickDASH trend', 'Task-specific tolerance'],
        },
      ],
      exerciseProgressionByStage: [
        {
          stage: 'subacute',
          exerciseProgressionIds: ['ex-shoulder-isometric-to-isotonic-abduction'],
          rationale: 'Bridges analgesic loading into strength-endurance progression for daily and sport demands.',
        },
      ],
      healingRecoveryTimeline: ['Irritability reduction in 2-6 weeks with consistent load management.', 'Functional recovery commonly 6-16 weeks depending on chronicity and workload.'],
      redFlagTopicIds: ['redflag-nonmechanical-night-pain-weight-loss'],
      commonMistakesPitfalls: ['Using provocative impingement tests as sole diagnosis.', 'Progressing overhead load despite >24-hour symptom flare pattern.'],
      evidenceSummary: 'Best-supported care combines education, load modification, and progressive exercise; passive modalities are adjuncts rather than central treatment.',
      referenceIds: ['ref-rcsp-cpg-2022', 'ref-hawkins-meta'],
      evidenceStrengthTags: ['high', 'moderate'],
      lastReviewed: {
        reviewer: 'Clinical Content Team',
        reviewedAtIso: '2026-03-31',
        nextReviewDueIso: '2027-03-31',
      },
    },
    {
      id: 'condition-adhesive-capsulitis',
      title: 'Adhesive Capsulitis',
      aliases: ['Frozen shoulder'],
      bodyRegionId: 'region-shoulder',
      clinicalSnapshot: 'Stiff painful shoulder with progressive capsular pattern ROM loss and disproportionate night symptoms.',
      typicalPattern: ['Global active and passive ROM restriction, especially external rotation.'],
      commonSubjectiveClues: ['Gradual onset stiffness', 'Marked limitation with grooming/dressing tasks'],
      objectiveExamPriorities: ['Confirm capsular pattern and compare passive vs active limits'],
      keyDifferentialConditionIds: ['condition-rcrsp'],
      specialTestIds: [],
      stageBasedManagement: [
        {
          stage: 'post-op-late',
          goals: ['Rebuild lower-quarter strength symmetry.', 'Prepare for higher-speed field/court demands.'],
          treatmentIds: ['tx-progressive-resistance-exercise'],
          progressionFocus: ['Unilateral strength', 'Deceleration and landing mechanics'],
          reassessmentPriorities: ['Effusion response', 'Strength and control benchmarks'],
        },
      ],
      exerciseProgressionByStage: [
        {
          stage: 'post-op-late',
          exerciseProgressionIds: ['ex-knee-quad-strength-control'],
          rationale: 'Provides structured bridge from basic squatting to unilateral control needed before running and cutting.',
        },
      ],
      healingRecoveryTimeline: ['Often prolonged recovery over 12-24 months with stage-dependent symptoms.'],
      redFlagTopicIds: [],
      commonMistakesPitfalls: ['Overloading painful stiff phase with aggressive high-irritability stretching.'],
      evidenceSummary: 'Education and staged mobility/loading are central, with referral options considered in refractory cases.',
      referenceIds: ['ref-rcsp-cpg-2022'],
      evidenceStrengthTags: ['moderate'],
      lastReviewed: {
        reviewer: 'Clinical Content Team',
        reviewedAtIso: '2026-03-31',
        nextReviewDueIso: '2027-03-31',
      },
    },
    {
      id: 'condition-acl-sprain',
      title: 'ACL Sprain / Tear (Acute)',
      aliases: ['Anterior cruciate ligament injury'],
      bodyRegionId: 'region-knee',
      clinicalSnapshot: 'Acute knee injury with rapid swelling, instability, and difficulty with pivoting/cutting tasks.',
      typicalPattern: ['Twist or deceleration injury with audible pop and quick effusion.'],
      commonSubjectiveClues: ['Immediate giving-way sensation', 'Loss of confidence with directional change'],
      objectiveExamPriorities: ['Effusion status', 'Lachman and related laxity tests when tolerated'],
      keyDifferentialConditionIds: [],
      specialTestIds: ['test-lachman'],
      stageBasedManagement: [
        {
          stage: 'post-op-late',
          goals: ['Rebuild lower-quarter strength symmetry.', 'Prepare for higher-speed field/court demands.'],
          treatmentIds: ['tx-progressive-resistance-exercise'],
          progressionFocus: ['Unilateral strength', 'Deceleration and landing mechanics'],
          reassessmentPriorities: ['Effusion response', 'Strength and control benchmarks'],
        },
      ],
      exerciseProgressionByStage: [
        {
          stage: 'post-op-late',
          exerciseProgressionIds: ['ex-knee-quad-strength-control'],
          rationale: 'Provides structured bridge from basic squatting to unilateral control needed before running and cutting.',
        },
      ],
      healingRecoveryTimeline: ['Time course depends on severity and operative/non-operative pathway.'],
      redFlagTopicIds: [],
      commonMistakesPitfalls: ['Relying on one laxity test without considering pain/guarding and mechanism.'],
      evidenceSummary: 'History + swelling behavior + laxity cluster improves diagnostic confidence over any single test.',
      referenceIds: ['ref-lachman-evidence'],
      evidenceStrengthTags: ['moderate'],
      lastReviewed: {
        reviewer: 'Clinical Content Team',
        reviewedAtIso: '2026-03-31',
        nextReviewDueIso: '2027-03-31',
      },
    },
    {
      id: 'condition-lateral-ankle-sprain',
      title: 'Lateral Ankle Sprain',
      aliases: ['ATFL sprain'],
      bodyRegionId: 'region-ankle-foot',
      clinicalSnapshot: 'Inversion injury with lateral ankle pain, swelling, and reduced load tolerance.',
      typicalPattern: ['Acute swelling and pain around ATFL/CFL region after inversion mechanism.'],
      commonSubjectiveClues: ['Pain with walking/turning', 'History of recurrent sprains'],
      objectiveExamPriorities: ['Rule out fracture needs first, then assess ligament tenderness and function'],
      keyDifferentialConditionIds: [],
      specialTestIds: ['test-ottawa-ankle'],
      stageBasedManagement: [
        {
          stage: 'subacute',
          goals: ['Restore baseline gait and calf capacity.', 'Rebuild ankle confidence in single-leg tasks.'],
          treatmentIds: ['tx-neuromuscular-balance-retraining', 'tx-progressive-resistance-exercise'],
          progressionFocus: ['Calf strength and proprioceptive progression', 'Introduce low-level hopping as tolerated'],
          reassessmentPriorities: ['Swelling trend', 'Single-leg balance quality'],
        },
      ],
      exerciseProgressionByStage: [
        {
          stage: 'subacute',
          exerciseProgressionIds: ['ex-ankle-calf-raise-progression'],
          rationale: 'Builds foundational ankle force and confidence before multidirectional loading.',
        },
      ],
      healingRecoveryTimeline: ['Most grade I-II sprains improve over weeks with progressive loading and balance retraining.'],
      redFlagTopicIds: [],
      commonMistakesPitfalls: ['Skipping fracture screen and returning to sport before force-control recovery.'],
      evidenceSummary: 'Use decision rules for imaging and combine with staged rehab for best outcomes.',
      referenceIds: ['ref-ottawa-ankle-rule'],
      evidenceStrengthTags: ['moderate'],
      lastReviewed: {
        reviewer: 'Clinical Content Team',
        reviewedAtIso: '2026-03-31',
        nextReviewDueIso: '2027-03-31',
      },
    },
  ],
};

export const clinicalSeedIndexes = buildClinicalIndexes(clinicalSeed);
export const clinicalReferenceMap = buildReferenceMap(clinicalSeed.references);

export function getConditionViewSamples(view: 'quick'): ConditionQuickView[];
export function getConditionViewSamples(view: 'deep'): ConditionDeepView[];
export function getConditionViewSamples(view: ViewDensity): Array<ConditionQuickView | ConditionDeepView> {
  return clinicalSeed.conditions.map((condition) => toConditionView(condition, view));
}
